### ISSUE TITLE
Create Folder Structure

### ISSUE THREAD

**Issue by danicaboe** [codeforpdx/PASS#10]

**Comment by danicaboe** [comment]
https://github.com/codeforpdx/PASS/tree/jk/solidPodBoilerplate

**Comment by colt-1** [comment]
🤝

**Comment by colt-1** [comment]
https://github.com/codeforpdx/PASS/tree/colton/pod-storage

**Comment by xscottxbrownx** [comment]
What is this issue?

There's no description, and links are broken.

**Comment by danicaboe** [comment]
You can delete it. It’s obsolete now.

Danica
