### ISSUE TITLE
SSL Certification expired for opencommons.net

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#105]
**Describe the bug**
The SSL certificate for opencommons.net so it's not possible to log with it as our Solid provider. Unable to log in because if it.

**To Reproduce**
1. Go to PASS
2. Attempt login
3. See problem (can't login)

**Expected behavior**
Log into PASS like normal.

**Comment by cotabas** [comment]
Whoever is in control of the domain, opencommons.net, and the server that inrupt is on needs to update the ssl. There are services like let's encrypt that will automatically update it for you.

This link explains how to setup inrupt with let's encrypt
https://docs.inrupt.com/ess/latest/installation/tutorial/use-production-lets-encrypt/
https://letsencrypt.org/getting-started/

hopefully this is helpful

**Comment by leekahung** [comment]
The issue with SSL seems to be fixed for https://opencommons.net. It has also moved over to Community Solid Sever. Closing issue.
