### ISSUE TITLE
Explore server-side functionality of Solid API

### ISSUE THREAD

**Issue by danicaboe** [codeforpdx/PASS#12]

**Comment by k-mack** [comment]
Work being done on https://github.com/codeforpdx/PASS/tree/km/spike/server-app.

**Comment by k-mack** [comment]
This is was paused due to lack of understanding of how this work meaningfully contributes to the project.

**Comment by leekahung** [comment]
Closing this issue in favor of more targeted issue related to server-side use case opened in the future.
