### ISSUE TITLE
Create/Regenerate Solid inbox on Login

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#132]
**Is your feature request related to a problem? Please describe.**
At the moment, we're using Node Solid Server which has a native inbox set to each new account. However,  I believe Community Solid Server has phased that out. When we finally move onto Community Solid Server, we would need a way to generate a dedicated inbox for users of PASS.

**Describe the solution you'd like**
A solution to this is to create a new function that builds an inbox container for the user's Pod on login and triggers only if container doesn't exist. At the moment, we could set the ACL exactly as it is in Node Solid Server, but we can tailor this in the future if needed.

**Comment by leekahung** [comment]
Currently being built in PR #148. Functionality for pulling data from Inbox in Solid to PASS has been completed. Waiting to build new inbox components in PASS.

**Comment by leekahung** [comment]
Existing system has a native inbox on Solid. However, Community Solid Server doesn't have one by design, so a function will need to be made to generate one similar to the outbox, but with different ACL settings like what we have now.

**Comment by xscottxbrownx** [comment]
Is this complete? Or am I misunderstanding what's left/needed?

**Comment by leekahung** [comment]
Almost, parts of it is still in PR #201

**Comment by leekahung** [comment]
The generation of Solid inbox has been completed as of PR #201 which was merged into Development. Issue resolved. Closing.
