### ISSUE TITLE
NewMessage as a modal

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#134]
**Is your feature request related to a problem? Please describe.**
We're currently have fixed form elements for our NewMessage component. We could have this to be like a modal instead.

**Describe the solution you'd like**
A solution for this would be to move form elements into an HTML `<dialog>` or into MUI modals. Would prefer the MUI route since we're migrating our styling over to that library.

**Comment by benzelcurry** [comment]
Completed as part of #issue-140 instead
