### ISSUE TITLE
PASS only allows one document of a type to be uploaded

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#135]
**Is your feature request related to a problem? Please describe.**
If I have already uploaded a document of a certain type (e.g. bank statement), and later try to upload another document of the same type, PASS will error and fail to upload the document correctly.

It will successfully upload the file (whatever the pdf or png is), but will not properly update the `document.ttl` or create a new `.ttl` for the new file.

**Describe the solution you'd like**
Restructure PASS file storage as the following:

- All files of a type are stored in their respective container
- Each type container can store multiple files of that type
- Each file has a respective `.ttl` file and `.acl` file
- Searches for document types return a list of all documents in that container

**Describe alternatives you've considered**
We could store all the `rdf` information in a singular `documents.ttl` file at the top of the container, but that could cause unnecessary data control issues. Simplest solution seems to be to give each file its own `.ttl` info.

Another possibility is to remove the type containers completely, and instead store the type in the `.ttl` file. This has impact on querying efficiency, although I haven't looked into RDF querying systems to know if this would make querying harder or easier. Querying also isn't a major aspect of the MVP (and probably wouldn't be a major aspect of the final product either), so I don't know if it's worth researching all that much.

**Comment by leekahung** [comment]
Related to #77.

**Comment by xscottxbrownx** [comment]
> Related to #77.

Is this and #77 the same?

Or is this one the "backend" functionality and #77 is the "frontend" functionality?

**Comment by timbot1789** [comment]
> > Related to #77.
> 
> Is this and #77 the same?
> 
> Or is this one the "backend" functionality and #77 is the "frontend" functionality?

They're not the same. Your backend and frontend comparison is a good way to think about it. You could implement the frontend form now, but if you tried to upload 2 bank statements, it would fail.

**Comment by xscottxbrownx** [comment]
> > > Related to #77.
> > 
> > 
> > Is this and #77 the same?
> > Or is this one the "backend" functionality and #77 is the "frontend" functionality?
> 
> They're not the same. Your backend and frontend comparison is a good way to think about it. You could implement the frontend form now, but if you tried to upload 2 bank statements, it would fail.

perfect, I was making sure I understood both of these issues correctly.

**Comment by leekahung** [comment]
Hey @timbot1789 I think we implemented one of the suggested solutions to this problem. We're currently using the following for our document uploads:

> We could store all the rdf information in a singular documents.ttl file at the top of the container, but that could cause unnecessary data control issues. Simplest solution seems to be to give each file its own .ttl info.

Let us know if you think we can close this.

**Comment by timbot1789** [comment]
This is done
