### ISSUE TITLE
PASS should allow multiple identity providers

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#136]
**Is your feature request related to a problem? Please describe.**
Currently, PASS only allows for one identity provider, the one configured in the `.env` file. However, it's likely PASS will need to interact with multiple identity providers. If the service is being used by the home insecure person, PASS should be able to connect to any identity provider the home insecure person uses. If the service is being used by a government organization, the case manager will still need to connect to the home insecure person's pod. 

**Describe the solution you'd like**
Allow the identity provider configured `.env` to still be the default identity provider, but allow the user to choose a different identity provider if they need.

**Comment by leekahung** [comment]
@timbot1789 I believe this issue has been largely addressed with recent updates to Development. Let me know if you think it still needs to be flushed out.

**Comment by leekahung** [comment]
Think this has been implemented fully in PR #169 allowing uses to utilizes other Solid Provider other than the one we've set by default. Believe this can be closed.
