### ISSUE TITLE
Enhance design and UX of InactivityNotification

### ISSUE THREAD

**Issue by benzelcurry** [codeforpdx/PASS#144]
### Enhancement

Improve the design and UX of InactivityNotification by blurring and preventing interaction with the background of the website while the modal is open, along with modifying the button color to match the rest of the website.

**Comment by xscottxbrownx** [comment]
@benzelcurry , while working on this issue...

If you want to look at `LogoutModal.jsx` for the MUI component inspiration,

OR 

if you find a better design/implementation/component, we can refactor that one to match.

**Comment by xscottxbrownx** [comment]
Completed with PR #166
