### ISSUE TITLE
Workflow - tag issues with pass project

### ISSUE THREAD

**Issue by murphynd** [codeforpdx/PASS#146]
**Is your feature request related to a problem? Please describe.**
In our current workflow, devs create an issue, assign it to themselves, and work on it without labeling unless they manually label it. and manually pick what project the issue relates to.  The problem is that those tickets float around on GitHub projects until they are labeled 'done' when they merge. This would automate the ticket labeling to the PASS project so it can be tracked and new users can pick up tickets on the project board. 

**Describe the solution you'd like**
I want to use GitHub actions and add a new workflow to create a label on issue creation. 

**Describe alternatives you've considered**
I considered telling the discord to label when creating a new issue, but automation is a better choice, and I need practice. 
**Additional context**

<img width="230" alt="image" src="https://github.com/codeforpdx/PASS/assets/25756547/8a59ed8c-b5b0-4f1e-b1b3-32cd5838869d">

**Comment by xscottxbrownx** [comment]
I like this idea, but am unfamiliar with github actions and projects. Seems pretty straightforward to me though.

So, I'll let others chime in for more experienced opinions.

**Comment by leekahung** [comment]
Will likely be incorporated to the workflow once it's merged into Master. Keeping this open for now in case it's not resolved.

**Comment by xscottxbrownx** [comment]
Is this complete?

**Comment by leekahung** [comment]
I think this is complete from the recent merge to Master. I'm going to close this issue.
