### ISSUE TITLE
Create button to clear selected user

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#159]
**Is your feature request related to a problem? Please describe.**
At the moment, the SelectUser context could be triggered by clicking "select" within the Users List component. However, how it works now is that it gets cleared after every form submission related to cross-pod interactions.

There could be cases where the user want to do multiple cross-pod interactions. Having the selected user state cleared after form submission (while fine in the case of single cross-pod interactions) defeats the point of a select user feature.

**Describe the solution you'd like**
We should create a button somewhere that lets users to explicitly clear selected user rather than having it auto-reset on form submissions.

**Comment by andycwilliams** [comment]
The MUI data grid component, which we used for the mockup and seems like the strongest option for the Users List, comes with its own `checkboxSelection` option.

https://mui.com/x/react-data-grid/

Could that help address this?

**Comment by leekahung** [comment]
Not sure. Have not seen it in action in conjunction with SelectUserContext. Personally, I think a button should suffice.

**Comment by leekahung** [comment]
Issue resolved in recent PR to Development (PR #246 ). Closing issue.
