### ISSUE TITLE
Rename UserList/UserSection to ClientList/ClientSection

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#160]
**Is your feature request related to a problem? Please describe.**
For PASS, UserList/UserSection was intended to help case-workers manage a list of clients. These components would eventually be hidden once we figure out how to distinguish different users using PASS. While clients are technically "users", it'll be more intuitive to rename these as ClientList/ClientSection.

**Describe the solution you'd like**
Simply rename sections related to UserList/UserSection to ClientList/ClientSection.

**Comment by xscottxbrownx** [comment]
@murphynd

I was just assigned to re-work this page of the app (Currently labeled as `HOME` in the `Navbar` - which is this `CLIENTS` page) with Laura from the UX team.   Were you working on renaming these components and the link in `Navbar` and almost ready to merge changes before I start making any code changes to these files?

I'm still in the research phase of learning what's all connected with this task and what it will require, so I'm not looking to start right this second.
