### ISSUE TITLE
Refactor styling from style.css into theme.js

### ISSUE THREAD

**Issue by andycwilliams** [codeforpdx/PASS#175]
With MUI installed, styling is now based on the `theme.js` sheet. In order to maintain consistency, consolidate the styling there and remove `style.css`.

**Comment by masenmatthews** [comment]
👋 I can pick this up! Not sure if I can assign the issue to myself or not. Should be able to start working on this tonight/tomorrow.

**Comment by leekahung** [comment]
Hey @masenmatthews. I've saw that in your branch (`masen-dev`), this removal has been done for a while now. Was curious as to why the changes were not proposed for a potential pull request? Are there still additional changes that still needs to be done?

**Comment by leekahung** [comment]
Issue as been resolve in PR #383. Closing issue.
