### ISSUE TITLE
Potential expansion of userList to include Notes

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#199]
**Is your feature request related to a problem? Please describe.**
At the moment PASS has properties for a user/clientList which contains information about the client such as familyName, givenName, podUrl, etc. But it could be useful to include a new property for case worker notes.

**Describe the solution you'd like**
What we can do here instead is simply add an empty "Notes" property when adding users and append new notes to it whenever a case worker adds one. Functionality for both these things would be required for the new JSON structure.

**Comment by timbot1789** [comment]
Closing as duplicate of: https://github.com/codeforpdx/PASS/issues/398
