### ISSUE TITLE
Deploy React app to project's GitHub Page via GitHub Actions

### ISSUE THREAD

**Issue by k-mack** [codeforpdx/PASS#20]
**Is your feature request related to a problem? Please describe.**
Automated deployments will eliminate the overhead of manual deployments.

**Describe the solution you'd like**
When a branch is merged into Master, the React App on Master is built and deployed to GitHub Pages.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by k-mack** [comment]
Note to self. `refs/heads/Master`, not `ref/heads/Master`.

**Comment by Jared-Krajewski** [comment]
fixed with <path: './dist'> change under upload frontend assets in ci.yml and adding <base: '/PASS/',> to vite.config.js
