### ISSUE TITLE
Document Selection Style Updates

### ISSUE THREAD

**Issue by andycwilliams** [codeforpdx/PASS#208]
Adding MUI styling to the "Document Selection" component (`DocumentSelection.jsx`), which is implemented by multiple other components. This has been kept as a separate issue in order to ease the process and reduce potential bugs.

To begin once all components using Document Selection are complete.

**Comment by leekahung** [comment]
Alright, although the changes were made earlier than expected, I think it got the job done in PR #236.

The DocumentSelection issue looks resolved and no further errors seems to appear in the branch.

Going to leave this open for a little longer until #234 is merged in case something does break.

**Comment by leekahung** [comment]
Current implementation of MUI Document Selection looks good so far. The only issue is that the value of Select is not correct yet, just the placeholder. Should be resolved in PR #243. Closing issue for now.
