### ISSUE TITLE
UI update for message preview

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#216]
**Is your feature request related to a problem? Please describe.**
The loading message preview component looks alright at the moment if it were to be used in mobile. However, for desktop, it'll have a lot of empty spacing to the right.

**Describe the solution you'd like**
Could perhaps format the message preview in the form `Sender - Title | Message snippet | Date` or `Sender - Title | Date | Message snippet` or something that could fill the space and revert to the original form for message preview at a certain breakpoint for mobile.

**Comment by andycwilliams** [comment]
Both Inbox and Outbox (or Messages, whenever they are both refactored into a single route) need to be restyled into MUI anyway, although I do not see an issue made for that yet.

Would it be better to create an issue for overall restyling and have this request be part of it?

**Comment by leekahung** [comment]
Combining Inbox and Outbox into a new page would be a different issue than styling Inbox and Outbox. Don't think we need to start one for styling until we actually combine them.

Unless you're thinking of styling individual pages.

But even then, they're separate from this issue, which is specifically for message previews.
