### ISSUE TITLE
Consolidate Inbox and Outbox Pages into Messages

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#217]
**Is your feature request related to a problem? Please describe.**
At the moment, Inbox and Outbox are independent routes to PASS, but can be consolidated to just one page called Messages.

**Describe the solution you'd like**
Consolidate Inbox and Outbox pages into Messages. Users would then be able to toggle between inbox and outbox components without routing using some sort of button or internal navigation within Messages.

**Comment by andycwilliams** [comment]
@timbot1789 Are you currently working on this? No one has been assigned to it yet.

**Comment by leekahung** [comment]
Have completed the merger of this issue into Development. Closing issue.
