### ISSUE TITLE
Get rid of styled components styling & switch to MUI in ClientListTable.jsx and ClientListTableRow.jsx

### ISSUE THREAD

**Issue by xscottxbrownx** [codeforpdx/PASS#219]
### Issue:

**currently have some leftover styling in `ClientListTable.jsx` and `ClientListTableRow.jsx` from first implementation**

---

### Direction:

change to MUI components and styling instead

<img width="517" alt="Screenshot 2023-06-06 at 12 59 06 PM" src="https://github.com/codeforpdx/PASS/assets/71395931/354fd684-56a0-4994-906a-e081efdd62fa">

<img width="527" alt="Screenshot 2023-06-06 at 12 59 27 PM" src="https://github.com/codeforpdx/PASS/assets/71395931/f9aaf5f3-3b13-4f27-95bc-2a897ba7a990">

**Comment by Sky-De** [comment]
Hi 
Where are those file?
Would you please mention dir to these two .jsx file

**Comment by xscottxbrownx** [comment]
> Hi Where are those file? Would you please mention dir to these two .jsx file

On `Development` branch...  src/components/Clients

**Comment by masenmatthews** [comment]
Hey @xscottxbrownx @Sky-De , is this being worked on? If not, could I have it assigned to me? Doesn't look like I have permissions to self-assign.

**Comment by xscottxbrownx** [comment]
^ Thanks andy, I missed this in email.

**Comment by andycwilliams** [comment]
Hi @masenmatthews. Just checking in. Have you made progress with this?

**Comment by masenmatthews** [comment]
Hey @andycwilliams, apologies for the delayed response! Yeah I've made some progress but have gotten a bit sidelined due to work and travel demands in the last couple of weeks. I'm out of town this week, but should be able to continue working on this next week. 

If this has increased in urgency, then it might be worth reassigning if there are resources available. I should have a lot more bandwidth to work on tasks and attend meetings consistently after roughly 7/25.

**Comment by leekahung** [comment]
Hey @masenmatthews was a bit curious as to the progress of this issue since it's related to PR #376. Let us know if you're still up to working on this issue. Thanks!

**Comment by xscottxbrownx** [comment]
Unassigned, been 2.5months with no seen progress and lack of responses

**Comment by masenmatthews** [comment]
@leekahung @xscottxbrownx 
Apologies for missing your previous message. Confirming that this can be reassigned.

**Comment by andycwilliams** [comment]
This is a good issue for a newer team member to take on but I can pick it up if nobody else wants to.

**Comment by leekahung** [comment]
Think we can assign the issue to the user with an active branch working on this.

**Comment by tomdieli** [comment]
I'll take a shot at this if no one else is working on it.

**Comment by andycwilliams** [comment]
> I'll take a shot at this if no one else is working on it.

You can but just so you know I'm currently converting `ClientListTable.jsx` and `ClientListTableRow.jsx` to MUI as part of #343. I can leave the refactoring of this styling itself to you. Just wanted to let you know in order to avoid conflicting branches.

**Comment by tomdieli** [comment]
@andycwilliams thanks for the info. I have no emotional attachment to this particular issue, and don't want to risk any unnecessary thrash. I will look for something else.

**Comment by milofultz** [comment]
Would be happy to jump in on this issue to get my feet wet in the project

**Comment by milofultz** [comment]
I am pretty sure this issue has been solved by [this PR](https://github.com/codeforpdx/PASS/pull/433).

[Here is the commit](https://github.com/codeforpdx/PASS/pull/433/commits/5b447b9d231eb1e53c87ef2a5f18dbe84d516ff7) that has the changes to the two `jsx` files mentioned above.

**Comment by leekahung** [comment]
Think we can close this as complete if this is finished @xscottxbrownx or us there still other things needed?

**Comment by bingeboy** [comment]
Sry I thought that my comment on the PR would auto close this ticket.

**Comment by xscottxbrownx** [comment]
> Sry I thought that my comment on the PR would auto close this ticket.

It's due to our default branch being Master, so issues won't close until code is merged into that branch...

I rose an issue for this suggesting we switch default branch to Development so issues close when PR is created to Development as is our typical flow.   Issue #430
