### ISSUE TITLE
 Make the alert popup on delete of client a MUI modal component (ClientListTableRow.jsx)

### ISSUE THREAD

**Issue by xscottxbrownx** [codeforpdx/PASS#223]
### Issue:

When clicking the `delete` icon in the table of clients, an alert message pops up to confirm.  Need to use an MUI modal and styling to match rest of app instead.

---

### Direction:

Take inspiration from our other MUI modals to have similar styling for this. 
`LogoutModal`, `AddClientModal` (which isn't 100% complete yet), and even `InactivityMessage` are all closely styled and fit within the app theme.

<img width="1232" alt="Screenshot 2023-06-06 at 2 58 12 PM" src="https://github.com/codeforpdx/PASS/assets/71395931/2563b8c4-1fd3-43a1-9c2b-7ba7751d4629">

**Comment by ajay2827** [comment]
@xscottxbrownx I am interested in this, can you assign this to me?

**Comment by xscottxbrownx** [comment]
> @xscottxbrownx I am interested in this, can you assign this to me?

Have you read this repo's readme's on contributing and such?   

When creating new branch from `Development` for this, make sure to start branch name with `issue-223/` followed by whatever you want to call branch (something like: "delete-client-modal")

**Comment by ajay2827** [comment]
@xscottxbrownx I have a made delete client modal and it works fine, I have attached a screenshot of it, could you review it, please?
![Screenshot 2023-06-16 150741](https://github.com/codeforpdx/PASS/assets/96379056/f25accb5-3152-44a9-b136-5a74580cacf6)

**Comment by xscottxbrownx** [comment]
> @xscottxbrownx I have a made delete client modal and it works fine, I have attached a screenshot of it, could you review it, please? 

Well, all I can do right now is see what it looks like from your screenshot.

Can you make a pull request, so I can test on local machine and look at the code?

---

And in the future, could you make sure you get assigned to the issue before proceeding?
You didn't get assigned because you never responded to my questions.

If an issue isn't assigned, other developers will think it's free to be worked on and it will lead to somebody wasting their time or merge conflicts.

**Comment by ajay2827** [comment]
> > @xscottxbrownx I have a made delete client modal and it works fine, I have attached a screenshot of it, could you review it, please?
> 
> Well, all I can do right now is see what it looks like from your screenshot.
> 
> Can you make a pull request, so I can test on local machine and look at the code?
> 
> And in the future, could you make sure you get assigned to the issue before proceeding? You didn't get assigned because you never responded to my questions.
> 
> If an issue isn't assigned, other developers will think it's free to be worked on and it will lead to somebody wasting their time or merge conflicts.

As a beginner to open source, I didn't know about it, but in the future, I will take care of it, thank you @xscottxbrownx for helping me.

**Comment by ajay2827** [comment]
> > @xscottxbrownx I have a made delete client modal and it works fine, I have attached a screenshot of it, could you review it, please?
> 
> Well, all I can do right now is see what it looks like from your screenshot.
> 
> Can you make a pull request, so I can test on local machine and look at the code?
> 
> And in the future, could you make sure you get assigned to the issue before proceeding? You didn't get assigned because you never responded to my questions.
> 
> If an issue isn't assigned, other developers will think it's free to be worked on and it will lead to somebody wasting their time or merge conflicts.

Now i made a pull request with the title Created DeleteClientModal, could you review, please

**Comment by xscottxbrownx** [comment]
> Now i made a pull request with the title Created DeleteClientModal, could you review, please

Thank you.

Also just another thing to help with GitHub use...   you can link to an Issue or PR  by using it's number.

So in this case you could add #257 and it would provide a link to the PR you created.   As soon as you type the `#` symbol it should popup a list for you to select from.   Just another tip.

**Comment by andycwilliams** [comment]
We may want to reassign this to @xscottxbrownx since he is now taking over responsibility.

**Comment by leekahung** [comment]
Assignment switched to @xscottxbrownx
