### ISSUE TITLE
Include new Archive system for messages

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#225]
**Is your feature request related to a problem? Please describe.**
Existing implementing for message have a dedicated inbox/outbox system with the ability to send each other message. However, it doesn't not have the ability to move messages to an archive or delete a message.

**Describe the solution you'd like**
Created an archive container that can be used for storing messages from inbox or outbox.

**Comment by timbot1789** [comment]
Not needed for MVP. We'll need to have some design discussions around when/where/how to add this. There are a lot of ways to implement archiving. At the very least we'd probably want to store it all in a compressed file of some kind.

**Comment by timbot1789** [comment]
Closing as won't be done
