### ISSUE TITLE
Update notification for message sent status

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#227]
**Is your feature request related to a problem? Please describe.**
Could be useful to include indicators that a message has been sent successfully or has failed from a sent message. We have something like that now, but UI can potentially be improved.

**Describe the solution you'd like**
Update to message sent status with MUI

**Comment by andycwilliams** [comment]
I've been looking at some MUI features and Snackbar seems like it could be a good use for this:
https://mui.com/material-ui/react-snackbar/

I've experimented with it a bit already. It's a highly customizable pop-up component and looks pretty good in my opinion.

Edit: It might also be an option to replace the existing status notifications in the forms.

**Comment by leekahung** [comment]
Can certainly look into it. The interface looks really nice having it pop up.

**Comment by leekahung** [comment]
Closing issue in favor of issue #216 and related to moving status notifications to MUI snackbar or equivalent.
