### ISSUE TITLE
Removing .env from repository

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#237]
**Is your feature request related to a problem? Please describe.**
Currently using `.env` to run our environment for the project, but we only want this locally, hence the inclusion in `.gitignore`.

**Describe the solution you'd like**
The `.env` are not meant to be use this so we'll want to remove this on the repo.

Developers would need to save a separate copy of `.env` into root from `env_templates/dev.env` after its removal from a git pull/git fetch

**Comment by timbot1789** [comment]
I can take care of this one. Although @leekahung I'll probably need to talk to you at some point about github pages env values.

**Comment by leekahung** [comment]
> I can take care of this one. Although @leekahung I'll probably need to talk to you at some point about github pages env values.

That would be good. Let me know of a good time to discuss.

**Comment by xscottxbrownx** [comment]
Closed with merging of PR #261
