### ISSUE TITLE
Replace Javascript's Date function with Day.js Date Objects throughout codebase

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#247]
# Update July 7, 2023 [Ka Hung]

Day.js will be the ISO-8601 compliant library we'll be using moving forward. We have the library installed in the project, we just need to replace the old JS Date Objects with the Day.js Day Objects.

---

## Original Post:

**Is your feature request related to a problem? Please describe.**
Currently for dates, we are using javascript's built-in `Date` library. However, this implementation is notoriously buggy, and does not comply with the ISO 8601 date format (the most widely-used date interchange format). Specifically, it does not correctly render timezone information when the timezone is missing. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#date_time_string_format

You can read a clearer discussion of this problem at the [linked blog post](https://maggiepint.com/2017/04/11/fixing-javascript-date-web-compatibility-and-reality/)

**Describe the solution you'd like**
Remove `Date` from our code and replace it with a javascript library that correctly implements the ISO 8601 spec. `moment.js` is the most popular library of this type.

**Describe alternatives you've considered**
There is work being done on a built-in library called [Temporal](https://tc39.es/proposal-temporal/docs/index.html), however it's not ready for production yet.

**Additional context**
The issue here is mostly around cross-platform and cross-timezone compatibility. As long as we only have javascript code using `Date` acting on PASS files, we should be fine. However, if we ever begin working with non-javascript code, and have users in multiple different timezones, the buggy `Date` implementation will start causing problems.

In fact, this may already be the case with the driver's license barcode scanner. I haven't tested it, but the dates on the barcode are ISO-8601.

**Comment by timbot1789** [comment]
Not something that's needed for MVP, but the sooner we deal with it, the easier it will be to fix. If PASS takes off, this issue will rear its ugly head in unexpected places.

**Comment by ajay2827** [comment]
@timbot1789 I am interested in this, can you assign this to me?

**Comment by xscottxbrownx** [comment]
> **Is your feature request related to a problem? Please describe.** Currently for dates, we are using javascript's built-in `Date` library. However, this implementation is notoriously buggy, and does not comply with the ISO 8601 date format (the most widely-used date interchange format). Specifically, it does not correctly render timezone information when the timezone is missing. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#date_time_string_format
> 
> You can read a clearer discussion of this problem at the [linked blog post](https://maggiepint.com/2017/04/11/fixing-javascript-date-web-compatibility-and-reality/)
> 
> **Describe the solution you'd like** Remove `Date` from our code and replace it with a javascript library that correctly implements the ISO 8601 spec. `moment.js` is the most popular library of this type.
> 
> **Describe alternatives you've considered** There is work being done on a built-in library called [Temporal](https://tc39.es/proposal-temporal/docs/index.html), however it's not ready for production yet.
> 
> **Additional context** The issue here is mostly around cross-platform and cross-timezone compatibility. As long as we only have javascript code using `Date` acting on PASS files, we should be fine. However, if we ever begin working with non-javascript code, and have users in multiple different timezones, the buggy `Date` implementation will start causing problems.
> 
> In fact, this may already be the case with the driver's license barcode scanner. I haven't tested it, but the dates on the barcode are ISO-8601.

Moment is already not being worked on, the creators don't recommend using it.  I used one of their alternatives listed "Day.js" in a previous project and it was real simple to use.

**Comment by timbot1789** [comment]
> @timbot1789 I am interested in this, can you assign this to me?

Assigned. Feel free to assign yourself to any issues you want to pick up too. We'll get updates.

**Comment by timbot1789** [comment]
> Moment is already not being worked on, the creators don't recommend using it. I used one of their alternatives listed "Day.js" in a previous project and it was real simple to use.

Oh ok. Haven't used moment in a little bit. Hadn't heard it got deprecated.

**Comment by leekahung** [comment]
I think Andy's working on getting `Day.js` installed in his updates to the date picker on the forms, we should be good to go.

https://github.com/codeforpdx/PASS/tree/issue-215/cross-pod-styling-updates

Feel free to have the package installed for this.

**Comment by andycwilliams** [comment]
`Day.js` has been installed into the Development branch as of #253

**Comment by andycwilliams** [comment]
Are we ready to close this issue?

**Comment by andycwilliams** [comment]
Unassigning due to inactivity

**Comment by leekahung** [comment]
Issue has been addressed in PR #304 which is now merged into Development. Closing.
