### ISSUE TITLE
Add File Viewer to PASS

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#250]
**Is your feature request related to a problem? Please describe.**
Currently, if a case manager wants to view a file on a client's pod, they must first download the file and then open it in a separate file viewer on their computer. This is a rather annoying workflow, as it requires the case manager to exit PASS. There's also a data privacy risk if the case manager doesn't clear the file from their downloads after viewing it.

**Describe the solution you'd like**
We can solve both issues by adding a file viewer to PASS. The case manager would be able to open and read the file without exiting PASS, and PASS would be able to enforce any privacy cleanup or viewing requirements it deems appropriate. We can still have the download link as an alternative flow, but add a popup to it that reminds them to delete the file after downloading. 

**Additional context**
We'd want to support at least these files: PDF, PNG, JPG

Some other additional file types: TXT, HEIC, TTL, TIFF

HEIC is quite difficult to support, but would be really useful to add. It's the image format Iphone uses, and Apple won't release a spec for it. Support for it is generally poor (safari doesn't support it), because apple won't release a spec for it.

**Comment by leekahung** [comment]
Think we could add .gif as well for additional file types.

**Comment by xscottxbrownx** [comment]
do you think .gif and .mov would be used for PASS?

**Comment by timbot1789** [comment]
> do you think .gif and .mov would be used for PASS?

Possibly. I think on first iteration we can focus just on file types that would be used to store the gov't documents we're most interested in. We can then enhance the file viewer later for other file types.

**Comment by leekahung** [comment]
Got something rudimentary created for this, but it's a start. Thinking of turning it into a draft soon. I already have the branch up.

https://github.com/codeforpdx/PASS/assets/14917816/5bb67a93-d5fd-4759-af87-763faa369f1c

**Comment by xscottxbrownx** [comment]
Yo, you've been a monster lately!

**Comment by leekahung** [comment]
PR for a file viewer merged into Development. Can consider doing an embedding of the document on iframes from the file Blob in the future PR. Closing issue for now..
