### ISSUE TITLE
Update the inactivity message and add force logout on inactivity

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#251]
# Update July 7, 2023 [Ka Hung]

We have implemented an extension for the inactivity message from 3 to 30 minutes. If the user is not active after 30, user is likely no longer active, we can forcefully log them out without issue. We just need to implement that as stated in original post.

> 3. Make the required period of inactivity longer (30 mins?) and forcibly logout the user after that time.

We can add an additional delay to warn users of impending logout (i.e. 5 minutes) before actually logging them out. Timing of warning message and forced logout can be discussed.

---

## Original Post

**Is your feature request related to a problem? Please describe.**
Currently, PASS shows an inactivity message after about 3 minutes. This is a rather short time. It's quite common for users to leave to grab a coffee, or just get caught up in a simple conversation and have the message appear. The message itself also doesn't do anything. Normally, these types of messages are used in sensitive systems where you are forced to log out after a period of inactivity. However, this popup does not do that.

This is also going to be annoying and intrusive in live demos, as there will certainly be periods of a few minutes in the demo where we are answering questions for 3 minutes.

**Describe the solution you'd like**
A few possible solutions:
1. Remove the inactivity message
2. Make the message less intrusive (maybe a warning banner at the top of the window?)
3. Make the required period of inactivity longer (30 mins?) and forcibly logout the user after that time.

**Additional context**
It's unclear at this stage what value the inactivity message adds to PASS. It is likely that PASS will be storing sensitive information, and will need to force user logout. However, we're not at that stage yet. There is also value in having a standard method of showing modals. An experiment in this activity message is helpful in that regard. At least we should bump the inactivity timer to ~30 minutes.

**Comment by xscottxbrownx** [comment]
I made a plea for number 3 a while back.  It seemed pointless to not have it automatically log the user out after the message was shown for certain amount of time.

I'm not positive on what the correct timeframes are (how long until message pops up, and how long once it's displayed until user is logged out), but user should be logged out or message doesn't serve any purpose.

**Comment by leekahung** [comment]
I think we can push for number 3 as well and extend the time for the notification.

At longer time scales, I think it's safe to assume that the person is no longer using the app, so forcefully log them out then would be fine. Before with the 3 minute time scale, a reminder would be the better choice.

**Comment by andycwilliams** [comment]
The inactivity timer has been extended to 30 minutes as of #260

**Comment by andycwilliams** [comment]
Now that number 3 is implemented, have we done everything we want in order to close this issue?

EDIT: I still back the idea of adding a countdown to automatically log out the user if no action is taken within a specified time (3 to 5 minutes).

**Comment by brancwill** [comment]
I can add a countdown and force logout after said countdown completes. Which would be better?

1. The inactivity message displays after 30 minutes with a countdown of 5 minutes on top of that.

2. The inactivity message displays after 25 minutes with a countdown of minutes, bringing the total time before log out to 30 minutes.

**Comment by xscottxbrownx** [comment]
> I can add a countdown and force logout after said countdown completes. Which would be better?
> 
> 1. The inactivity message displays after 30 minutes with a countdown of 5 minutes on top of that.
> 2. The inactivity message displays after 25 minutes with a countdown of minutes, bringing the total time before log out to 30 minutes.



I think either would be fine, but I think my personal preference would be option 2.

@andycwilliams @leekahung @Jared-Krajewski - thoughts?

**Comment by leekahung** [comment]
> > I can add a countdown and force logout after said countdown completes. Which would be better?
> > 
> > 1. The inactivity message displays after 30 minutes with a countdown of 5 minutes on top of that.
> > 2. The inactivity message displays after 25 minutes with a countdown of minutes, bringing the total time before log out to 30 minutes.
> 
> 
> 
> I think either would be fine, but I think my personal preference would be option 2.
> 
> @andycwilliams @leekahung @Jared-Krajewski - thoughts?

Same opinion on 2, but either is fine.

**Comment by andycwilliams** [comment]
I prefer option 1 but I'm okay with either

**Comment by Jared-Krajewski** [comment]
> > > I can add a countdown and force logout after said countdown completes. Which would be better?
> > > 
> > > 1. The inactivity message displays after 30 minutes with a countdown of 5 minutes on top of that.
> > > 2. The inactivity message displays after 25 minutes with a countdown of minutes, bringing the total time before log out to 30 minutes.
> > 
> > 
> > I think either would be fine, but I think my personal preference would be option 2.
> > @andycwilliams @leekahung @Jared-Krajewski - thoughts?
> 
> Same opinion on 2, but either is fine.

option 2. [these guidelines](https://pages.nist.gov/800-63-3/sp800-63b.html#sec7l) seems to recommend action at 30 minutes, so 25 + 5 of countdown hits that mark. <img src="https://drive.google.com/uc?id=1TjDGWqHX7jSVhOAi9aBxjeOGZDOUkImL">

**Comment by leekahung** [comment]
Issue resolved in PR #341. Closing issue.
