### ISSUE TITLE
Show something other than table headers if no documents in user's pod

### ISSUE THREAD

**Issue by xscottxbrownx** [codeforpdx/PASS#266]
## Issue:
This is what currently renders if a user does not have any documents in their pod:
<img width="1375" alt="Screenshot 2023-06-20 at 8 42 15 AM" src="https://github.com/codeforpdx/PASS/assets/71395931/168ff1eb-459a-414d-b170-4cfce4284a8b">

---

## Proposed solution: 
1. Make matching red notice like in `Clients`
or
2. Make a more polished notice component for this, and use in both `Clients` and `Forms`

**Comment by leekahung** [comment]
Think we could have an indicator of some sort which says it's currently empty like what we have for ClientList.
