### ISSUE TITLE
Move Upload Document into button/modal combo

### ISSUE THREAD

**Issue by xscottxbrownx** [codeforpdx/PASS#269]
## Issue:

Currently, `UploadDocumentForm.jsx` is at top of `Forms` page/route. 

https://github.com/codeforpdx/PASS/assets/71395931/9cdaaafa-ea16-4ac2-8194-33e4bf8e9da7

---

## Proposed Solution:

Top of this page/route should be a button to upload a new document, which would open `UploadDocumentForm.jsx` in a modal.  This way the user's eyes are actually drawn to their documents that render in the table.

**Comment by andycwilliams** [comment]
Normally I want to stick to one thing at a time, but this is close enough to the issue I'm currently working on that (#218 ) that I'd like to tackle it too.

I will finish that one first, then move on to this.
