### ISSUE TITLE
Snapshot bug for OidcLoginComponent.test.jsx

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#280]
**Describe the bug**
While the test passes when checked on GitHub, the snapshot seems to fail when it checks for it locally using `npm run test`. It could be related to the environment variables being used.

**Expected behavior**
To pass in both GitHub and locally.

**Comment by leekahung** [comment]
Hey @timbot1789, I believe this has been worked on recently with the updates to Development? Think we can close this if you think it's been patched up.

**Comment by timbot1789** [comment]
Oh yeah this was finished.
