### ISSUE TITLE
Various improvements to README.MD and CONTRIBUTING.MD

### ISSUE THREAD

**Issue by Jared-Krajewski** [codeforpdx/PASS#283]
**Is your feature request related to a problem? Please describe.**
With advancements in the project and a lot more activity, improvements and updates to README and CONTRIBUTING files were needed.

**Describe the solution you'd like**
Improve formatting, clarity of project goals, and more direct steps for contributing as a new member. Ideally making the project seem more welcoming to future contributors. 

**Describe alternatives you've considered**
Receive input from active participants to see what seemed lacking when they joined and could be improved.

**Additional context**
see branch for documentation_changes

**Comment by leekahung** [comment]
Related to #147. Think I'll close that one and leave this one opened.

**Comment by Jared-Krajewski** [comment]
> Related to #147. Think I'll close that one and leave this one opened.

whoops, sorry for duplicate issue. I thought there was one created for it and started looking around but still somehow missed it.

**Comment by timbot1789** [comment]
I think the first section in the readme should be dev install instructions. How to get it up and running on your system so you can poke around it.

Currently we require Node version 16 or higher and NPM for our package manager.  Most places recommend using a node version manager to install node and npm. I like NVM. So steps would be:

1. Clone the git repository: `git clone https://github.com/codeforpdx/PASS.git`
2. Download NVM for your system. Find instructions here: https://github.com/nvm-sh/nvm
3. Install node version 16: `nvm install 16`
4. Use that node version: `nvm use 16`
5. Check that node and npm are set up:
  `node -v`
  `npm -v`
If either of those commands error, node has not been installed correctly.
6. Install project dependencies: `npm install`
7. Run the project: `npm run dev`
8. PASS should launch at `http://localhost:5173`. You can now visit that url, and sign into a pod hosted at the OIDC provider of your choice.

**Comment by leekahung** [comment]
We've recently created a small diagram for a tech stack. Think we can incorporate that to the new README.

**Comment by Jared-Krajewski** [comment]
> We've recently created a small diagram for a tech stack. Think we can incorporate that to the new README.

I saw this in the changes to contributing.md, I will move it into the Readme with the tech stack.

**Comment by Jared-Krajewski** [comment]
> I think the first section in the readme should be dev install instructions. How to get it up and running on your system so you can poke around it.
> 
> Currently we require Node version 16 or higher and NPM for our package manager. Most places recommend using a node version manager to install node and npm. I like NVM. So steps would be:
> 
> 1. Clone the git repository: `git clone https://github.com/codeforpdx/PASS.git`
> 2. Download NVM for your system. Find instructions here: https://github.com/nvm-sh/nvm
> 3. Install node version 16: `nvm install 16`
> 4. Use that node version: `nvm use 16`
> 5. Check that node and npm are set up:
>    `node -v`
>    `npm -v`
>    If either of those commands error, node has not been installed correctly.
> 6. Install project dependencies: `npm install`
> 7. Run the project: `npm run dev`
> 8. PASS should launch at `http://localhost:5173`. You can now visit that url, and sign into a pod hosted at the OIDC provider of your choice.

I can add this in. Do you think this is best for the Readme or should be in contributing as part of the setup for development?

**Comment by timbot1789** [comment]
> > I think the first section in the readme should be dev install instructions. How to get it up and running on your system so you can poke around it.
> > Currently we require Node version 16 or higher and NPM for our package manager. Most places recommend using a node version manager to install node and npm. I like NVM. So steps would be:
> > 
> > 1. Clone the git repository: `git clone https://github.com/codeforpdx/PASS.git`
> > 2. Download NVM for your system. Find instructions here: https://github.com/nvm-sh/nvm
> > 3. Install node version 16: `nvm install 16`
> > 4. Use that node version: `nvm use 16`
> > 5. Check that node and npm are set up:
> >    `node -v`
> >    `npm -v`
> >    If either of those commands error, node has not been installed correctly.
> > 6. Install project dependencies: `npm install`
> > 7. Run the project: `npm run dev`
> > 8. PASS should launch at `http://localhost:5173`. You can now visit that url, and sign into a pod hosted at the OIDC provider of your choice.
> 
> I can add this in. Do you think this is best for the Readme or should be in contributing as part of the setup for development?

I think the readme is a perfect place for putting the instructions for dev setup. If I were just coming to the project blind, I wouldn't look to the contributing section for how to run the program. That seems like an unnecessary step. No one is going to be looking at our readme if they aren't trying to run the project from source, so why hide those instructions?  Here's what github has to say about the topic: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes#wikis

I've always seen READMEs used as "here's what you need to get the program up and running, and here are some key ways to use it."

We can then have links at the bottom of the readme to documents like how to contribute and app architecture, but the readme itself IMO we can keep fairly terse.

**Comment by Jared-Krajewski** [comment]
> > > I think the first section in the readme should be dev install instructions. How to get it up and running on your system so you can poke around it.
> > > Currently we require Node version 16 or higher and NPM for our package manager. Most places recommend using a node version manager to install node and npm. I like NVM. So steps would be:
> > > 
> > > 1. Clone the git repository: `git clone https://github.com/codeforpdx/PASS.git`
> > > 2. Download NVM for your system. Find instructions here: https://github.com/nvm-sh/nvm
> > > 3. Install node version 16: `nvm install 16`
> > > 4. Use that node version: `nvm use 16`
> > > 5. Check that node and npm are set up:
> > >    `node -v`
> > >    `npm -v`
> > >    If either of those commands error, node has not been installed correctly.
> > > 6. Install project dependencies: `npm install`
> > > 7. Run the project: `npm run dev`
> > > 8. PASS should launch at `http://localhost:5173`. You can now visit that url, and sign into a pod hosted at the OIDC provider of your choice.
> > 
> > 
> > I can add this in. Do you think this is best for the Readme or should be in contributing as part of the setup for development?
> 
> I think the readme is a perfect place for putting the instructions for dev setup. If I were just coming to the project blind, I wouldn't look to the contributing section for how to run the program. That seems like an unnecessary step. No one is going to be looking at our readme if they aren't trying to run the project from source, so why hide those instructions? Here's what github has to say about the topic: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes#wikis
> 
> I've always seen READMEs used as "here's what you need to get the program up and running, and here are some key ways to use it."
> 
> We can then have links at the bottom of the readme to documents like how to contribute and app architecture, but the readme itself IMO we can keep fairly terse.

I added it in. I will also check out what i can do to shorten things up. Most likely moving other technical/resource information to another document that will be linked.

**Comment by xscottxbrownx** [comment]
Lines 2, 51, and 59 have different opening and closing element tags (somebody needs to install the Auto Rename Tag vscode extension 😆)

Line 49 typo "maintain documentats"

Are we using the id's for anything? If not can just take out the element tags for headings altogether and use the straight markdown (`#` for h1, `##` for h2, etc)

**Comment by Jared-Krajewski** [comment]
> Lines 2, 51, and 59 have different opening and closing element tags (somebody needs to install the Auto Rename Tag vscode extension 😆)
> 
> Line 49 typo "maintain documentats"
> 
> Are we using the id's for anything? If not can just take out the element tags for headings altogether and use the straight markdown (`#` for h1, `##` for h2, etc)

adding that extension thanks. 😆 those errors I had just noticed and the changes will push in the morning with a few others. It was giving me issues linking for the table of contents, couldn't figure out why some of the links worked and some didn't so I used the h tags with id. Turns out it was an extension I had causing the issue and It is now all in MD.

**Comment by Jared-Krajewski** [comment]
changes merged in #290
