### ISSUE TITLE
Limiting size of file uploaded onto PASS for profile images

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#289]
**Is your feature request related to a problem? Please describe.**
At the moment, users can simply upload a file of any size for their profile picture, given that it's an accept file for upload (i.e. ".png", ".jpeg", ".gif", etc.).

**Describe the solution you'd like**
Perhaps we could introduce a size limit to file upload.

**Comment by russfraze** [comment]
I put an if check for this in the UploadDocumentForm. Right now its set to 8MB ( I am assuming the file size is in bytes ), but I'm not sure what the final consensus was from the last dev meeting.

**Comment by leekahung** [comment]
I don't think we got a consensus about the file size, but I think up to 10MB seems reasonable. But would need more input from others. I'm not really sure.

**Comment by timbot1789** [comment]
I don't think PASS needs to worry about this right now. This is a database concern, and PASS currently is not a database, it's a UI. Our clients, the case managers and the citizens, run the database. They will be able to set their own upload size constraints on the backend, regardless of what we put in PASS.

I can see 2 possible ways to address this:

1. We implement an environment variable `MAX_UPLOAD_SIZE` that different clients can set to whatever is appropriate for their system
2. We allow uploads of any size, but prepare for servers to reject uploads. Then we can simply display an error to the user. `Upload failed. Reason: ${whateverReasonTheServerGaveUs}`. We don't control the server, so the server can reject for any reason it wants already. The file is too big, the agent has exceeded their maximum pod size, they've uploaded too many documents in the past second, they're not allowed to upload on tuesdays. As a UI, PASS can only do so much.


Note: We already have handling for the second case

**Comment by xscottxbrownx** [comment]
Shall we discuss soon, and decide either to close this issue or a direction for it?

**Comment by timbot1789** [comment]
@xscottxbrownx I think we can leave this open, but mark it as stalled or blocked. Someone asked about this in the Solid app-development gitter recently (basically a discord forum hosted by inrupt):


> Hi all, is there a standardised way for a pod to report to an agent what the maximum allowed file upload is? I'm running into an issue with node solid server where our nginx proxy is rejecting requests because of the payload size. In this specific case I can increase the max_body_size in our nginx but of course that's only going to help with my server, and will potentially fail if a user comes with a different provider with a smaller limit. We can add error checking to see if a file fails to upload, but this is going to be an HTTP 503 from nginx with no semantic data in the response. Could this be something that a user's profile indicates along with ws:storage?

The only response said:
> Not that I'm aware of, I'm afraid

What we can do in PASS is make sure to display an error message whenever the server rejects an upload, but I think that's a different issue.

**Comment by leekahung** [comment]
I agree with @timbot1789. Think we could backlog this for now and un-assign this until it's worked on in an active branch.

**Comment by ogorman89** [comment]
@leekahung I like the idea of a practical limit for profile images.  So I can implement this if you still want it done. 

I propose to add a check file size check to `handleProfileImage`. I'll display an error message using the `useNotification` hook if the file exceeds the limit. 

What should our size constraints be for profile images 1MB? 5MB?

**Comment by leekahung** [comment]
> @leekahung I like the idea of a practical limit for profile images. So I can implement this if you still want it done.
> 
> I propose to add a check file size check to `handleProfileImage`. I'll display an error message using the `useNotification` hook if the file exceeds the limit.
> 
> What should our size constraints be for profile images 1MB? 5MB?

I think 1MB should be enough for a small 100px by 100px avatar.
