### ISSUE TITLE
Creating PASS-specific marker for file uploads via PASS

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#291]
**Is your feature request related to a problem? Please describe.**
While PASS wouldn't have control over the user's Pod with regards to file uploads (e.g. user can use another Solid application to upload onto their Pod), was wondering if we could place PASS-specific "markers" for files uploaded via PASS to distinguish between what files are upload via PASS and what files are uploaded via other applications.

**Describe the solution you'd like**
Not sure if it's possible, but a solution to this would be to create a PASS-specific "watermark" for files being uploaded onto a Pod via PASS.

While we can't really limit a user from uploading files onto their Pod, but we could also include the uploader's webId to the upload file meta data in order to establish a potential "upload limit" for clients using PASS. This would restriction would only limit file uploads from PASS.

**Comment by timbot1789** [comment]
Closing as duplicate
This can be done using the credentialing system described in this issue:
https://github.com/codeforpdx/PASS/issues/259

We don't need to worry about if a doc was uploaded via PASS. We can instead worry about if a document was uploaded or viewed by a certain user. They can then attach that credential to the uploaded document
