### ISSUE TITLE
Allow expiration dates earlier than the current date

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#294]
## Update - Aug 16, 2023

Previously issue was looking to disallow expiration dates, but thinking further there could be times when users simply wanted to store their old document onto their Pod storage. For these older documents with expirations dates past current date, we could simply display a warning somewhere in the row for the documents table to indicate that it's expired or a warning somewhere near the expiration date.

**Comment by cameronabel** [comment]
There is a pretty simple tweak to the MUI DatePicker component to restrict past dates from being selected. Is this something that we want to do via scripting in addition to just modifying the selector? A creative user can wipe the MUI classes off the html element and it seems to accept a past date just fine:

![image](https://github.com/codeforpdx/PASS/assets/56567967/63e2f77a-6c03-4eef-b1eb-c954c11cff0f)

**Comment by leekahung** [comment]
@andycwilliams I've left the opening description blank since I'm not sure of the details when it was a draft, feel free update and fill in what your original idea was. @cameronabel would be interested in working on this.

**Comment by xscottxbrownx** [comment]
> There is a pretty simple tweak to the MUI DatePicker component to restrict past dates from being selected. Is this something that we want to do via scripting in addition to just modifying the selector? A creative user can wipe the MUI classes off the html element and it seems to accept a past date just fine:

Are you saying people can get around the `disablePast` prop?

**Comment by xscottxbrownx** [comment]
I think the `onError` styling and `helperText` would also be ideal to add during this PR

https://mui.com/x/react-date-pickers/validation/#show-the-error

**Comment by cameronabel** [comment]
> > There is a pretty simple tweak to the MUI DatePicker component to restrict past dates from being selected. Is this something that we want to do via scripting in addition to just modifying the selector? A creative user can wipe the MUI classes off the html element and it seems to accept a past date just fine:
> 
> Are you saying people can get around the `disablePast` prop?

Yes. The screenshot in my post above was taken with `disablePast` enabled. I was then able to use the browser dev console to strip the field of all MUI classes and upload a file with a past expiration date.

**Comment by leekahung** [comment]
I'm still somewhat hesitant about this idea.

Of course, users would probably want to upload their latest documents in order to be verified and validated for certain services, so the idea would be useful in those cases.

But I could also see a case where users just want to upload their older documents for storage purposes regardless of expiration.

**Comment by timbot1789** [comment]
I kind of agree with Ka Hung's last comment. I don't really see a value in preventing a user from uploading an expired document. Maybe display a warning in the documents table if it is expired?

**Comment by xscottxbrownx** [comment]
shall we discuss soon and decide to either close this issue, or a direction for it?

**Comment by ogorman89** [comment]
Based on the user population, I think they need to store expired docs. A scan of an expired passport for example is still a valuable form of identification. 

Maybe this isn't necessary, but could we just add a warning ⚠️ icon to the document upload form if an expiration date earlier than the current date is selected? We could also display the document status with the same icon on the document table.

**Comment by ogorman89** [comment]
> ## Update - Aug 16, 2023
> Previously issue was looking to disallow expiration dates, but thinking further there could be times when users simply wanted to store their old document onto their Pod storage. For these older documents with expirations dates past current date, we could simply display a warning somewhere in the row for the documents table to indicate that it's expired or a warning somewhere near the expiration date.

Basically exactly what @leekahung updated the issue to on Aug 16th.

**Comment by leekahung** [comment]
Hey @cameronabel how's progress going with regards to this issue?

**Comment by ogorman89** [comment]
@leekahung I have an idea for this one; I'll take a stab at it too.

**Comment by timbot1789** [comment]
@ogorman89 did you implement a PR for this? If so we can close this issue.

**Comment by ogorman89** [comment]
@timbot1789 Apologies, I forgot about this one. 

The only reason this is still open was that I was going to add a notification if a user tried to upload an expired document. Something like the screenshot below. 

After thinking about it more, I think it's better without the warning.

If you agree, then I say we close it for now.

![warn](https://github.com/codeforpdx/PASS/assets/3335277/cd2ee612-c00f-4ee8-b087-477482d5603b)

**Comment by timbot1789** [comment]
> @timbot1789 Apologies, I forgot about this one.
> 
> The only reason this is still open was that I was going to add a notification if a user tried to upload an expired document. Something like the screenshot below.
> 
> After thinking about it more, I think it's better without the warning.
> 
> If you agree, then I say we close it for now.
> 

No worries. And yeah that sounds like a different issue to me. Basically "how should we display expired documents to users?" I like your idea of a notification, but we may also want to display something in the doc table itself.
