### ISSUE TITLE
Research: DataPODS

### ISSUE THREAD

**Issue by htharker42** [codeforpdx/PASS#3]
Research the DataPODS data infrastructure and the type of tooling that would be required to integrate this system. 
Research how to integrate PDF or email files into this system.

**Comment by k-mack** [comment]
Below are some experiments that should help us understand the Solid ecosystem.

- [x] Setup: `1 IDP, 1 Pod provider, 1 file browser application, 2 users`; Goal: `share a file`
- [x] Setup: `1 IDP, 1 Pod provider, 2 file browser applications, 2 users`; Goal: `use a different application with Pod data`
- [ ] Setup: `1 IDP, 2 Pod providers, 1 file browser application, 1 users`; Goal: `1 user, multiple pods`
