### ISSUE TITLE
Profile Hamburger menu disappears when navigating to documents page

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#300]
**Describe the bug**
In our mobile, small screen configuration, we have a hamburger menu on the far right side of the screen that contains profile, notifications, etc...

![Screenshot from 2023-07-10 18-14-02](https://github.com/codeforpdx/PASS/assets/37914436/1a2aea35-23ba-4b6c-ab1b-4633d3fd3484)

However, this menu disappears when you are on the Documents page:

![image](https://github.com/codeforpdx/PASS/assets/37914436/1b05b5c0-ced9-4acc-85c4-530ad6dcc85a)

It should not disappear

**Comment by xscottxbrownx** [comment]
@timbot1789 is there any more context you can give? I cannot recreate issue.


https://github.com/codeforpdx/PASS/assets/71395931/aaab7fc9-e525-4a64-96c8-d0a0d026b104


On your second screenshot, there is a scrollbar for left and right. Is it just all the way to the right?

**Comment by timbot1789** [comment]
@xscottxbrownx 

Here's a video of what I mean. Happens on mobile size displays, or if the browser is only at half screen.

[Screencast from 07-11-2023 08:55:56 AM.webm](https://github.com/codeforpdx/PASS/assets/37914436/70b7b3cd-2afa-444e-9057-2be22319ec13)

**Comment by xscottxbrownx** [comment]
Scroll to the right - it's because the tables aren't optimized for mobile yet so it extends the screen and you have a scroll bar on bottom to go to the right more.

Are you thinking it's better to be `width=100vw` ?

**Comment by timbot1789** [comment]
The resolution I'm using is actually just a half-screen window on my laptop, so not at a mobile resolution yet.

![image](https://github.com/codeforpdx/PASS/assets/37914436/7d37de95-f074-4b40-9fa1-7ae7910bf471)

I'm thinking it's better if the navbar display doesn't change based on what page you're on. You're right, there are multiple workarounds, so this isn't an important fix. I'm mostly dropping this here because it would be a good onboarding task for someone new to the project. 

The issue seems to be that the doc page is overflowing to the side, and pushing the navbar with it. Adding `width=100vw` to the navbar does seem like a reasonable approach.

**Comment by xscottxbrownx** [comment]
Resolved with PR #323
