### ISSUE TITLE
DocumentTableRow window.confirm to MUI modal

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#316]
**Is your feature request related to a problem? Please describe.**
Current component for `DocumentTableRow` uses window.confirm to alert users of deleting document. This could be updated to use a modal.

---
**Describe the solution you'd like**
NEW DIRECTION:
create a `ConfirmationModal` that can be used any place we just need a "are you sure you want to do this?" notification with a "cancel" and "confirm" button.

---
This `ConfirmationModal` should be able to replace:
`LogoutModal`
`DeleteContactModal`
`DeleteDocumentModal` <-- first attempt at solving this Issue.

**Comment by xscottxbrownx** [comment]
Little stalled while waiting for PR #392 + PR #388 to be finished up.  But most of code is there and just waiting for these to be complete so I can complete this one.
