### ISSUE TITLE
Navbar and layout breaks down before limit for mobile

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#324]
**Bug Description**:
As shown in the clip below, the Navbar and Layout for PASS breaks below a certain screen width and before we even reach what was decided as the lower limit for our project (320px).

https://github.com/codeforpdx/PASS/assets/14917816/7edb2910-230a-4f83-a0cb-3463c8f70ed9

**Expected Behavior**:
Layout and Navbar should be responsive up to our limit, fully filling out the screen.

**Possible Solution**:
Update Navbar, Layout, and any other potential components to be responsive down to 320px screen width.

**Comment by xscottxbrownx** [comment]
Resolved with PR #323
