### ISSUE TITLE
Update PASS color scheme

### ISSUE THREAD

**Issue by andycwilliams** [codeforpdx/PASS#329]
**Describe the Current Behavior/Feature**:
To date, PASS has used a placeholder color scheme. It is fine for development but does not follow UX guidelines and will ultimately need an update. The PASS UX team is creating a theme that better suits this app's specific needs.

**Proposed Behavior/Feature**:
Replace the current color scheme with the one developed by the UX team.

**Rationale**:
A guiding principle for the app is to be trauma-informed. Colors can have effects that affect the user, such as calming them or causing additional stress. The new color scheme will incorporate that philosophy.

**Proposed Implementation (if applicable)**:
`theme.js` contains the styling which applies to the whole app. Only that file will need to be changed.

**Additional context**:
The different palette options in `theme.js` have fields for `light` and `dark`. Those are not currently part of the MVP. Updating `main` should be the focus.

**Comment by leekahung** [comment]
Temporarily un-assigning task for now until UX team got theming finalized.

**Comment by timbot1789** [comment]
@andycwilliams Is this ticket still relevant? If we're still waiting on a UX design, can we close this ticket and write up a new one when the design is ready?

**Comment by andycwilliams** [comment]
> @andycwilliams Is this ticket still relevant? If we're still waiting on a UX design, can we close this ticket and write up a new one when the design is ready?

I'd like to revisit this in the future, but I haven't heard any updates in a long time. So I'm fine with closing it for now and reassessing sometime down the line.
