### ISSUE TITLE
[Open Discussion] Device camera uploads

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#335]
**Feature Description**:
Leaving this as an open discussion for the idea about uploading documents/images from a device after capturing an image of it. It's been a feature that's been discussed with the PASS team and other collaborators that it could be a useful feature to have, but we have yet to implement it.

Currently, PASS allows for file uploads directly from the device's/browser's file explorer. But there could be times when users simply want to capture an image and upload that image into storage instead.

**Possible Solution**:
One way we could go about it is to create an option to upload images from device to PASS on "Upload Documents" and utilize the `getUserMedia` function from the `MediaDevices` web API.

Another way to go about this is to use input's native capture attribute from HTML to trigger the device's camera.

**Comment by leekahung** [comment]
Issue have been touched in PR #357. But keeping this issue opened in case of further changes or improvement in this implementation, i.e. desktop camera.

**Comment by timbot1789** [comment]
@leekahung this can be done pretty easily with the HTML `capture` attribute
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/capture
Then we can have it on any device. I think we can add the following feature:

- If the browser detects an available camera, a "camera" button is added to the PASS document upload form. The user can click on the button and take a photo with the "environment" camera, and upload the photo to their pod.

**Comment by leekahung** [comment]
> @leekahung this can be done pretty easily with the HTML `capture` attribute
> https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/capture
> Then we can have it on any device. I think we can add the following feature:
> 
> - If the browser detects an available camera, a "camera" button is added to the PASS document upload form. The user can click on the button and take a photo with the "environment" camera, and upload the photo to their pod.

I believe I've experimented a bit with capture the previous time I've messed with media devices (see initial commits in #357). It worked pretty well before I've decided to use the other solution.

Could be a good first issue for someone.

**Comment by Zakeriya23** [comment]
@leekahung Wondering, if I could finish researching and opitmizting this issue?

**Comment by leekahung** [comment]
> @leekahung Wondering, if I could finish researching and opitmizting this issue? 

Sure, give it a shot!

**Comment by Zakeriya23** [comment]
I'm having trouble pushing my code into the issue branch I created. But I wanted to keep everyone updated on the situation. I utilized the camera library and made new modals to display the webcam. The end product is shown in the photo below. Once my pushing issue is handled, I comment the branch and commit I make. 


![Screenshot 2023-10-31 221637](https://github.com/codeforpdx/PASS/assets/87618816/f0e97345-d91e-4a3c-8453-4fe2cb225d27)
![Screenshot 2023-10-31 221652](https://github.com/codeforpdx/PASS/assets/87618816/5de16974-bbf7-4ebe-ad55-fb680a56d9c9)

**Comment by leekahung** [comment]
> I'm having trouble pushing my code into the issue branch I created. But I wanted to keep everyone updated on the situation. I utilized the camera library and made new modals to display the webcam. The end product is shown in the photo below. Once my pushing issue is handled, I comment the branch and commit I make. 
> 
> 
> ![Screenshot 2023-10-31 221637](https://github.com/codeforpdx/PASS/assets/87618816/f0e97345-d91e-4a3c-8453-4fe2cb225d27)
> ![Screenshot 2023-10-31 221652](https://github.com/codeforpdx/PASS/assets/87618816/5de16974-bbf7-4ebe-ad55-fb680a56d9c9)


Thanks for the updates @Zakeriya23 ! From the screenshot you've shown, it's looking great! 👍

I have some time tomorrow if you'd like to discuss about the push issue. Feel free to ping me on the Discord server.

**Comment by Zakeriya23** [comment]
Created a PR #498, but had some failed tests. Please give me any suggestion by looking into the branch 335 I created.
