### ISSUE TITLE
Enhancement: Update PASS header to have logo and be clickable

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#337]
**Describe the Current Behavior/Feature**:
Currently in the navbar, we have the word PASS in the upper left corner of the navbar. It's in the same space as an App logo is normally. However, no logo is present, and unlike many apps, the text does not navigate you back to the home screen.

![image](https://github.com/codeforpdx/PASS/assets/37914436/ce852a43-16f9-4d68-a9b8-5c64d1c515f0)

**Proposed Behavior/Feature**:
Replace the PASS text with a clickable icon that navigates you back to a home page in the app. Similar to how the github logo navigates you to the github home page.

**Rationale**:
A logo will make the app look more professional, and a clickable logo is a common feature in many websites that users will probably be familiar with.

**Comment by sagargoyal-bit** [comment]
Can you assign it to me?, i want to work on it

**Comment by timbot1789** [comment]
@sagargoyal-bit assigned the issue to you. Are you in the PASS discord? If so, message Hauvert. He has a good logo design to use here. I'd link him to this, but I'm not sure what his github handle is.

**Comment by Raspber** [comment]
Send me a message in discrd and i will send it to you,.

**Comment by leekahung** [comment]
Issue resolved in merge to Development PR #348. Closing issue.
