### ISSUE TITLE
Inactivity Notification no longer appears

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#339]
**Bug Description**:
Currently we have an inactivity notification set in place through the InactivityMessage component (InactivityMessage.jsx). However, one of the states that causes notification rendering `activeUser` no longer get set to `true` since `loggedIn` is no longer being stored in localStorage. This causes the notification to never pop-up even if `showPopup` is `true`.

**Potential Solution**:
We could simply replace the localStorage.getItem("loggedIn") with `session.info.isLoggedIn`.

**Comment by brancwill** [comment]
In my pull request I've updated the inactivity notification with `useSession` and removed `activeUser`.

**Comment by leekahung** [comment]
Issue resolved in PR #341. Closing issue.
