### ISSUE TITLE
Enhancement: Update Contacts View to display Contact Cards instead of Table

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#343]
**Describe the Current Behavior/Feature**:
Recent updates have compressed the amount of information displayed in the client's table. It now looks like this:
![image](https://github.com/codeforpdx/PASS/assets/37914436/f01d0f76-9c69-4a7f-821e-d0f079b45273)

Not very much useful information displayed there.

Our figma mockups also display something else here. Instead of a table, we have a list of cards for each client. We can then click on the client to go to their profile.

**Proposed Behavior/Feature**:
We already have a similar card displayed on the profile page:
![image](https://github.com/codeforpdx/PASS/assets/37914436/c481f7d4-9f26-4944-8acb-8da50d94fa62)

We could use these cards in place of the table rows to display client information

**Comment by leekahung** [comment]
Not exactly in the form of cards like that shown from our Figma designs and that mentioned in this issue, but I've made some headways with MUI's Data Grid to allow for filtering and better sorting in PR #457.
