### ISSUE TITLE
Render permissions forms on profile page as modals after an onClick event only

### ISSUE THREAD

**Issue by xscottxbrownx** [codeforpdx/PASS#358]
### Describe the Current Behavior/Feature:
Both "set permissions" forms are rendered on the Profile Page currently.

---
### Proposed Behavior/Feature:
Ideally, these would be modals/dialogs that popup after an onClick event attached to a button or icon.

---
### Rationale:
**1.** To clean up the profile page and bring the focus to the user's info and documents only.
**2.** To have the "set permission to a specific file" be more obviously linked with a specific file - modal renders after an onClick of something in that file's row on the documents table.
**3.** To be more consistent with rest of app ("Add Client", "Add Document", etc)
**4.** Second step in getting these forms into the final version we actually want them to be.

---
### Proposed Implementation (if applicable):
Follow similar structure of the `AddClientModal` or `UploadDocumentModal` files - using what we've already built into the "set permissions forms" files.

**Comment by brancwill** [comment]
I can make dialogs and buttons for those.

**Comment by xscottxbrownx** [comment]
> I can make dialogs and buttons for those.

Give it a shot if you'd like.

**Comment by leekahung** [comment]
Issue resolved in recent PR #388. Closing issue.
