### ISSUE TITLE
Scripting issue with ESLint and Prettier for Windows 11

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#368]
### Bug Description:
ESLint and Prettier appears to have issues with running on Windows 11. It couldn't seems to find the matching pattern when compared to Mac OS and Linux when running `npm run lint` or any related scripts with single quote `'`

---
### Reproduction Steps:    
**1.**   Use a Windows computer
**2.**  Attempt to run `npm run lint`
**3.**  See issue

---
### Expected Behavior:
To run ESLint and Prettier similar to how it is on Mac OS and Linux.

---
### Actual Behavior:
It errors out by not finding the correct matches.

---
### Desktop (please complete the following information):
 - OS: Windows 11

---
### Possible Solution (optional):
Have discussed and tested solution with Hauvert on his computer which is using Windows. The solution to this is to run ESLint and Prettier with double quotes `"`. This solution also works for Mac OS and Linux.

https://github.com/codeforpdx/PASS/assets/14917816/0c2921b1-6a97-4990-bfab-6b5ea34c370a

**Comment by Raspber** [comment]
![Screenshot 2023-08-02 220159](https://github.com/codeforpdx/PASS/assets/20136800/0a44639a-6f3a-402c-9e62-b433325f7507)
Here an image the error on Windows 11 with single quotes `'`

**Comment by Raspber** [comment]
Here is the solution.
![Screenshot 2023-08-02 220801](https://github.com/codeforpdx/PASS/assets/20136800/3824bce4-f8d5-428d-95a4-893062b3cb77)

**Comment by leekahung** [comment]
Issue resolved in PR #368. Closing.
