### ISSUE TITLE
Enhancement: Add git hooks to run linter and unit tests

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#373]
### Describe the Current Behavior/Feature:

We have several automated tests that run on PRs. eslint, prettier, vitests, etc. We don't allow commits to enter the project if these tests don't pass. However, when developing, it can be annoying to run all these manually. It's very easy to forget to run these tests, and only find out you have failures when you create a PR. This slows down code reviews.
Additionally, if a new member is merging from a fork, the PR tests don't run until another maintainer comes by and manually activates them. This makes it difficult to know that they need to run these tests _at all_.

---
### Proposed Behavior/Feature:
A popular package called [Husky](https://www.npmjs.com/package/husky)  is designed to solve these problems. It allows us to run commands on a git commit. If a test fails, the commit is blocked. We can configure this to run `eslint`, `prettier`, and `vitest`. The same commands that are being run in our github workflows.

**Comment by eathren** [comment]
Everything added, 13 tests currently broken, which would ironically block this from passing if I hadn't committed with the --no-verify flag. Progress can be seen at branch feature-husky-prettier-eslint-tests, and I'll nibble more on it later this week to see if those tests are failing for valid reasons or not. 

Some eslintrc rules updated, some deps moved.

**Comment by eathren** [comment]
Update, those tests also fail on main.

**Comment by timbot1789** [comment]
@nolanbraman I just ran your branch, and didn't see any tests failing. What tests are you seeing fail? And what system are you testing on?

**Comment by nolanbraman** [comment]
I was on WSL. After swapping to a new branch tonight on ubuntu, only two tests were failing for credentials-helper.test.js and Document.test.js. 

Removing   `window.crypto = webcrypto;` line allows tests to successfully complete since it triggers a getter/setter error. 

New branch is 373-husky-precommit-prettier-linter. I believe if we just remove that code completely, it doesn't seem to have any ill effect, and leaves the test suite at 100% pass rate

**Comment by nolanbraman** [comment]
Tisk. Until I finished setup and use node v16, that credentials-helper test fails since that var was needed.

**Comment by nolanbraman** [comment]
Scratch my previous comments. Using the 'right' version of node makes the tests pass.

**Comment by eathren** [comment]
@timbot1789 I was on WSL and looks like that was causing problems. On my ubuntu laptop and node v16, looks like tests run squeaky clean on a fresh branch off of Master. 

PR is up here with that fresh branch. https://github.com/codeforpdx/PASS/pull/385

**Comment by timbot1789** [comment]
This is complete. We've eliminated the test runner feature for now due to poor performance from vitest.
