### ISSUE TITLE
Transition from styled components to MUI for DocumentListTable.jsx and DocumentListTableRow.jsx

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#376]
### Describe the Current Behavior/Feature:
Currently we have an issue already opened for ClientListTable and ClientListTableRow to be updated from styled components to MUI in #219. However, `DocumentListTable.jsx` and `DocumentListTableRow.jsx` utilizes a lot of the same stylings. If the styling gets updated there, we would also need to update DocumentListTable and DocumentListTableRow as well during the transition.

---
### Proposed Implementation (if applicable):
Simply need to update DocumentListTable and DocumentTableListRow as well during the swap from styled components to MUI.

**Comment by leekahung** [comment]
Hey @cameronabel, just wanted to check up on the progress of this.

**Comment by leekahung** [comment]
Think I'll unassign this for now. Let me know when activity for this issue picks up again, I'll have this re-assigned.

**Comment by bingeboy** [comment]
@leekahung I'll grab this issue also

**Comment by leekahung** [comment]
> @leekahung I'll grab this issue also

Pick one and start from there

**Comment by bingeboy** [comment]
@leekahung ok I'll start with #408

**Comment by leekahung** [comment]
> @leekahung ok I'll start with #408

If you think you could handle both issues and work on them, I'm fine with assigning this to you as well. 👍

We've been having issues recently where people gets assigned a task, but not end up working on them with little to no response back when checking up on the progress.

**Comment by andycwilliams** [comment]
@bingeboy Are you currently working on this? If so, would you like to be assigned?

**Comment by bingeboy** [comment]
@andycwilliams I haven't started it yet
