### ISSUE TITLE
Create inputs for private profile information

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#377]
### Feature Description:
In PASS, the user's profile utilizes the public profile to fill out the "Profile" page. There could be certain things that should remain private such as date of born, mailing address, etc. As such, we need to create a separate file that stores the user's profile information that's not under "/profile" on Solid and have them available to fill out by the user in their "Profile" page on PASS.

Allowing case workers to view this information via permissions could be done separately in a follow-up issue/PR.

---
### Proposed Solution:
Create a privateProfileInfo.ttl somewhere in `/PASS` (perhaps in a new Profile container, i.e. `/PASS/Profile`).

**Comment by leekahung** [comment]
The first initial input (date of birth) has been created for PASS private profile. Going to leave this open however as an open issue for discussions of additional inputs.

**Comment by timbot1789** [comment]
Closing this in favor of https://github.com/codeforpdx/PASS/issues/440
