### ISSUE TITLE
Build functionality for cross pod interactions

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#38]
**Is your feature request related to a problem? Please describe.**
Still need to implement cross pod querying/writing

**Describe the solution you'd like**
Porting the existing vanilla versions in the project and refactoring them for React.

**Describe alternatives you've considered**
None at this moment.

**Additional context**
None at this moment.

**Comment by leekahung** [comment]
Have explored how much the new linting settings on #37 would affect code. Managed to narrow the number of problems to 26 locally after modification of code base with base settings, but 15 of these are still lint errors. Will be discussed with Greg and Jared when discussing rules for linting. Reverted previous commit to issue #40 that explores linting.

**Comment by leekahung** [comment]
Progress has been made in #40 with regards to cross pod interactions. In recent commits, we've managed to:

1. Create function to generate ACL file upon file upload and set ACL perms to user's pod automatically
2. Developed an interface to set ACL perms (either give or revoke) to other users for document type (only read access is provided at this time)
3. Developed an interface to query/search for that document type after permission is given

Functionality to cross pod write is still being built and explored at the moment.

**Comment by leekahung** [comment]
Might leave cross pod write out at the moment until we know where to store these files from other Pods and simply merge existing functionalities to Development.

**Comment by GoodGuyGregory** [comment]
I think it would be easier to merge the Linting changes you have from the code I started

**Comment by GoodGuyGregory** [comment]
I'm fine with whatever preferences we have they can always be changed/modified

**Comment by leekahung** [comment]
#38 is now completed with #40 merged into Development.
