### ISSUE TITLE
Current user profile card is displayed when no Client profile card is found

### ISSUE THREAD

**Issue by jlaurentpdx** [codeforpdx/PASS#386]
### Bug Title:
Current user profile card is displayed when no Client profile card is found

---
### Bug Description:
When an active user visits a link to a client's profile and the client does _NOT_ have a valid WebID associated with their username, the active user's profile card is displayed. 

---
### Reproduction Steps:    
**1.** When logged in as a current user, navigate to the `Clients` page
**2.** From `Clients`, select `+ Add Client`
**3.** Enter all necessary form data, being sure to leave the generated WebId in-place; then, click "**Add Client ✓**"
**4.** From the table displaying all current Clients, follow the link to the newly-created Client's profile by clicking on their name as displayed in the table

If these steps are followed correctly, you should now see the `Profile Card` matching the current user 

---
### Expected Behavior:
Expected behavior is unclear, but some considerations for content to display might include:

1. a "blank" profile card that includes the client's name, nickname, and a placeholder image
2. a "No Profile Found" card
3. a form to assist the Case Worker or Organization with level-appropriate profile-editing for the client
4. a guide to assist clients with creating or accessing their pod and profile information 

---
### Actual Behavior:
The Profile Card of the current user (Case Worker) is displayed on a page that should contain information related only to the newly-related Client.

---
### Screenshots (If applicable):

https://github.com/codeforpdx/PASS/assets/32883553/fd56a273-deca-4cfc-bee7-6e620927a9f2

---
### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Brave (Chromium), Firefox
 - Version: Brave v1.57.47 (Chromium 116) | Firefox 116.0.3 

---
### Smartphone (please complete the following information):
_N/A_

**Comment by leekahung** [comment]
Issue resolved in recent merge to Development in PR #402.
