### ISSUE TITLE
Revamp Home Page

### ISSUE THREAD

**Issue by andycwilliams** [codeforpdx/PASS#389]
### Describe the Current Behavior/Feature:
To date, the Home Page has been minimal and lacking in information.

---
### Proposed Behavior/Feature:
Update the current Home Page (a box with that simply states "HOME PAGE") with a more detailed one.

---
### Rationale:
Home pages benefit from informing users, particularly first-time ones, about the background and features of the app. They also provide a welcoming and appealing initial experience.

---
### Proposed Implementation (if applicable):
The UX team is in the process of designing a home page. The assignee should consult with them before beginning work.

**Comment by Raspber** [comment]
![Screenshot 2023-08-07 132304](https://github.com/codeforpdx/PASS/assets/20136800/0ec6eb31-82d1-435d-aad0-f14da8941dac)
I believe i can also do this as well. Along with the footer issue. Will update this with gabbys version of layout and colors and submit a pr.

**Comment by Raspber** [comment]
I will be submitting a pr for this issue tomorrow if I still havent heard back from Yoonisali. I have already completed this. Was waiting for Yoonisali to see if we would collab.
