### ISSUE TITLE
Enhancement: Update app footer

### ISSUE THREAD

**Issue by andycwilliams** [codeforpdx/PASS#393]
### Describe the Current Behavior/Feature:
Much of the app footer is currently a placeholder. For example, the "Proposal" button leads nowhere, the social media links are not properly connected, there's no tagline or logo, etc.

---
### Proposed Behavior/Feature:
Fill out all the missing information. Make sure it properly links to all relevant sites. Update the layout as well, if that is needed.

---
### Rationale:
Apps shouldn't have broken links or incomplete information. The user should be able to properly access everything that's presented to them.

---
### Proposed Implementation (if applicable):
Discuss with leadership to ensure what information should be included. Especially since it will link to terms and conditions as well as the privacy policy. Also, confirm the layout with the UX team.

---
### Additional context:
Add any other context or screenshots about the enhancement request here.

**Comment by Raspber** [comment]
![Screenshot 2023-08-07 132304](https://github.com/codeforpdx/PASS/assets/20136800/d0f26027-d682-4d2a-9647-137d217f9a7b)
I think i can do this. I will update this use gabbys updated version for colors and layout. I just havent submitted a pr

**Comment by andycwilliams** [comment]
> ![Screenshot 2023-08-07 132304](https://user-images.githubusercontent.com/20136800/263019131-d0f26027-d682-4d2a-9647-137d217f9a7b.png) I think i can do this. I will update this use gabbys updated version for colors and layout. I just havent submitted a pr

Go for it. And feel free to assign yourself.

**Comment by xscottxbrownx** [comment]
@Raspber did you say you were working on this and the home page?

**Comment by Raspber** [comment]
> @Raspber did you say you were working on this and the home page?

Yes, I am currently working on this.

**Comment by xscottxbrownx** [comment]
> > @Raspber did you say you were working on this and the home page?
> 
> Yes, I am currently working on this.

ok, I am going to assign it to you, along with the home page one.

**Comment by xscottxbrownx** [comment]
Will create new issue when we get finalized design on everything.  Updated for now with our current needs.

**Comment by andycwilliams** [comment]
I was thinking about creating an updated issue for this since we are still missing proper links but wanted to check in first. 

Perhaps at least we could updated the `https://www.codeforpdx.org/` destinations to `https://www.codepdx.org/`.
