### ISSUE TITLE
Enhancement: Add a login modal to select pod provider

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#412]
Currently, when you log into PASS, you are required to add the pod provider url to provider field. This field is prepopulated from the `.env` file, however, if you want to change to a different provider, you need to put the full URL in manually, which can be annoying. It's also confusing for newcomers, who don't know what URL to put in that form.

![image](https://github.com/codeforpdx/PASS/assets/37914436/dc29d0f8-8a5a-4771-bed5-490397214165)

Instead, we can still prepopulate the field with the url from the `.env` file, but then provide a list of common options if they want to pick something else. 

### Possible designs
A dropdown like podpro.dev would be good, clean way to do this
![image](https://github.com/codeforpdx/PASS/assets/37914436/28b38291-704e-4167-a2c8-9d64df42d7d5)

We could also use a large modal like solidcommunity.net, but that's a bit heavier
![image](https://github.com/codeforpdx/PASS/assets/37914436/f847d0d8-89c8-4849-aa8b-b7d394f9257d)

**Comment by andycwilliams** [comment]
What if we used a dropdown menu and also moved pod selection inside the login modal itself? I think that would make the home page look just a little bit cleaner.

**Comment by xscottxbrownx** [comment]
> What if we used a dropdown menu and also moved pod selection inside the login modal itself? I think that would make the home page look just a little bit cleaner.

As in, delete the text input from navbar & have modal popup when click login button?   This modal has filled in text input with the `.env` file - but option to select others?  Sort of like a combo of both screenshots provided above?

Is my understanding of your suggestion correct?

**Comment by timbot1789** [comment]
> What if we used a dropdown menu

We could, but I'd like to keep the number of clicks as low as possible. Right now it's one click if you want to sign into the default provider: login. If you want to select a different pod provider, it's several extra inputs. I'd like to keep it:

- 1 click to log into the default pod provider
- 2-3 clicks to log into a common (non-default) pod provider
- freetext to log into an uncommon pod provider

From how I understand your design, it seems to me that login would be two clicks: first click open modal, second click login.

**Comment by andycwilliams** [comment]
@xscottxbrownx Sorry, completely failed to reply in a reasonable time. Basically yeah, but now I'm rethinking it.

@timbot1789 Makes sense. My thinking was essentially what's in that last screenshot though I didn't necessarily articulate myself the best. I agree though that it perhaps does feel a bit clunkier than it has to be.

**Comment by rioredwards** [comment]
I'm going to get to work on this if that's alright! I'll go off of the podpro.dev design.
