### ISSUE TITLE
Enhancement: Add "Message" action to contacts list

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#414]
Currently, the contacts list only has a few actions: go to pod, pin contact, and delete

![image](https://github.com/codeforpdx/PASS/assets/37914436/e8471315-ae28-4bd8-aeb9-97c36cd2960c)

Another useful action to have on this table would be to message the client. Add a button to each contact in this list that launches  the "send message" modal when clicked, that prepopulates the "to" field with the webId of the contact.

**Comment by andycwilliams** [comment]
Since I'm already working on #343 I can just pick this one up too. I think it'd be easier that way.

**Comment by andycwilliams** [comment]
So I added the modal and now am setting it up to populate the `To:` field. What is the most efficient way to do this? Would it be to utilize the `oldMessage` parameter (I'm guessing via `message.recipientPodUrl` in the new message modal)?

**Comment by timbot1789** [comment]
You should be able to pull the value of the `to` field from the webId of the contact, in the contactsList. Take a look at `src/hooks/useContactsList.js`.
