### ISSUE TITLE
Bug: Signup page errors when signing up new pod

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#420]
### Bug Title: [Bug] Signup page errors when signing up new account

---
### Bug Description:

At the moment, there seems to be an issue when attempting to sign up a new pod. Was not able to reproduce what was shown in PR #378 before it was merged into Development.

---
### Reproduction Steps:    

See clip below.

---
### Expected Behavior:

Allows people to sign-up for new account

---
### Actual Behavior:
What actually happened, and how it differed from the expected behavior.

---
### Screenshots (If applicable):

https://github.com/codeforpdx/PASS/assets/14917816/0d0bd183-74a1-40ed-91e9-49482f02d231

**Comment by leekahung** [comment]
@bingeboy

**Comment by bingeboy** [comment]
I'm getting a similar error after successfully signing up with the form.
Seems to be an issue with `useContactList.js`  

Steps to create the error:
Browser FF Node v16.2

1. Start dev pod and dev server on localhost
2. From homepage http://localhost:5173 click LOGIN button sign into the pod
3. Once the user landing page loads click the link Your Signup Link
4. Create a sign in
5. When the page loads with You have successfully registered for a pod the error should be seen in the console.
6.  XHR requests that are throwing an error 409

**Comment by Aspireve** [comment]
Hey Hi @leekahung 
Could I work on this issue?

**Comment by Aspireve** [comment]
Hey Hi!!
I just cloned your repo and tried solving this bug, however I guess another new bug has developed, I am actually now not being able to open the Login Screen after pressing the Login button on the navbar
Could you suggest what should I do?
This is the error I'm getting

![image](https://github.com/codeforpdx/PASS/assets/93852415/dfae94c6-8d9b-4dc8-810f-794c11bea84a)

**Comment by leekahung** [comment]
Hey @Aspireve. With regards to that error, I think it's due to the local environment not set up correctly. Please check your .env file. If you manage to get the environment set up, you should get the following (assuming you've entered into a valid Solid server).

https://github.com/codeforpdx/PASS/assets/14917816/8007afe4-d992-487e-b7cd-768975de92e3

**Comment by Aspireve** [comment]
Ohh cool!! I was now able to login with a Solid Id.
Could you tell me how to sign up for a new account on the website so I could find the page where the bug resides?

**Comment by Aspireve** [comment]
Ohh I just found it lol.

**Comment by Aspireve** [comment]
Heyy @leekahung 
I did a bit more research, I don't think it is possible to register two accounts on the same Solid Pod
At the point when I am trying, its giving a 409 (conflict) error, which reveals that there can be only one profile for one pod at a time
And for registering a new account you need to get a new pod via the Solid System (the way we created our first account)

**Comment by leekahung** [comment]
> Heyy @leekahung 
> I did a bit more research, I don't think it is possible to register two accounts on the same Solid Pod
> At the point when I am trying, its giving a 409 (conflict) error, which reveals that there can be only one profile for one pod at a time
> And for registering a new account you need to get a new pod via the Solid System (the way we created our first account)
> 

I believe there's a bit of a misunderstanding here. What was attempted here was simply registering a new account for someone on Solid, not their own Pod (please check out PR #378). It'll be assigned their own webId and their own Pod on Solid, and their webId would be added to your contact list on your Pod. What was shown here was simply the bug that appears when attempting to do that. Though I'm not too sure if this bug still exist since I've been seeing other people able to register new accounts on their dev servers.

**Comment by Aspireve** [comment]
Ohh so I'm guessing this issue is solved then?

**Comment by leekahung** [comment]
> Ohh so I'm guessing this issue is solved then?
> 

I believe so since I haven't encountered that error as of late. Think I'll close down this issue as resolved? Might have been fixed in one of the earlier PRs related to the sign up flow.

The discussion on Issue #464 seems to be the most recent and relevant with regards to the sign up feature. I'll refer you to that.

**Comment by leekahung** [comment]
Closing issue.
