### ISSUE TITLE
Incorrect jsDoc comments in `AddContactModal.jsx`

### ISSUE THREAD

**Issue by xscottxbrownx** [codeforpdx/PASS#422]
### Bug Title:
Fix incorrect jsDoc in `AddContactModal.jsx`

---
### Bug Description:
The jsDoc for `renderWebId` function at top of file is inaccurate.
The jsDoc for `AddContactModal` is inaccurate.

**Comment by mallick03** [comment]
Hello! I would like to work on this issue.

**Comment by leekahung** [comment]
Linking PR #485 since it touches on this.
