### ISSUE TITLE
[DISCUSSION]: Change GitHub default branch to Development

### ISSUE THREAD

**Issue by xscottxbrownx** [codeforpdx/PASS#430]
### Bug Title:
GH Issues must be closed manually

---
### Bug Description:
Our current default branch in GH is set to `Master`, this means issues do not close until code has been merged into the `Master` branch - therefore all issues are currently closed manually when merging PRs into `Development.`

---
### Expected Behavior:
If default branch is set to `Development` and either use keywords of "close, closes, closed, fix, fixes, fixed, resolve, resolves, resolved" OR manually linking an issue (from the side menu/info),  then when a PR is merged it will automatically close that issue as well. See [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-re) and [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-or-branch-to-an-issue-using-the-issue-sidebar)

---
### Additional Context:
It could be fair to say the issue is not really resolved, until it is resolved in the `Master` branch. This is why I am opening this for discussion.  But, we are closing issues once they are resolved in the `Development` branch - so if we continue that way I propose we change the default branch to `Development`. GH instructions [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch)

**Comment by Jared-Krajewski** [comment]
We essentially only used development because we wanted master to host the latest "live" version for GH pages. I think the new deployment also pulls from master so it is probably still a good idea to switch it to Development for the incremental small pushes with weekly or bi-weekly push to master. I think when this was briefly brought up in a meeting a few weeks ago the general agreement was to switch to development.

**Comment by timbot1789** [comment]
I'm fine with this. I don't think there are any integrations that would break from this change.

**Comment by xscottxbrownx** [comment]
It seems people are in agreement from comments here and discussions in person, but I don't have admin access to this repo to be able to change this setting.

Maybe @Jared-Krajewski or @leekahung?  Do either of you have ability to click settings in top bar and switch default branch to `Development`?

**Comment by leekahung** [comment]
I'll have the default branch switched up to `Development`

**Comment by leekahung** [comment]
Have the default branch switched up to `Development` from `Master`. Closing issue #430.
