### ISSUE TITLE
Create HMIS Profile editing page + form framework

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#438]
## Details:
When we sign up users for PASS, we want to get certain information about them. The more information we can collect about a person, the better able case managers will be to provide services. For this purpose, we want to create a registration workflow where a user can create a profile. This profile will need to contain a large amount of information (we will try to collect most of the data allowed in [this data ontology](https://hmis-interop.github.io/)), and so we will need a fairly sophisticated registration flow. For this issue, I'd like to do the following things:

1. Create a new tab in PASS called "HMIS Profile" that navigates you to this page
2. This page should be under the route `/hmis_profile` (use react router)
3. The page should display:   - On the right a form card that will serve as a placeholder for a basic info form. 
  - On the left there should be a sidebar allowing you to select different forms (housing status, employment history, etc). 
  - On the bottom should be next and previous buttons allowing you to navigate to the next or previous forms in the list.
![image](https://github.com/codeforpdx/PASS/assets/37914436/7ee278e2-46a1-4d16-8f18-aacb4c1567ef)

## Additional considerations

- The driving goal of this UI is to make it very easy for a user to put in a large amount of optional, highly personal, and sometimes emotionally damaging information (e.g. history of domestic abuse). We want to make it easy for a user to skip over or ignore a section that is not relevant to them, or that they simply don't want to fill out right now.

## Additional information
- You may be able to use the [Material UI stepper component](https://mui.com/material-ui/react-stepper/) to implement the form progression
- I am not strongly attached to any particular UI design. If you have an idea to clean this up, please feel free to suggest it.
- I am generally basing this design off of tax software like [tax slayer](https://www.taxslayer.com/)

**Comment by bingeboy** [comment]
For this feature I'd assume we are going to lean heavy on ReactRouter? Setup an `<Outlet />` and another router for this section?

**Comment by timbot1789** [comment]
> For this feature I'd assume we are going to lean heavy on ReactRouter? Setup an `<Outlet />` and another router for this section?

That would be ideal, yes. Having a separate route for each step of the form would let us leverage browser history and caching more.
