### ISSUE TITLE
HMIS Profile Page: Basic Information Form

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#442]
## Feature Description:
Implement the first form (basic information) for the HMIS profile page. We need this form to collect four pieces of data, and store them with the corresponding data tags:

Field Name | Field Type | Profile Predicate value
- First Name | Text Input | urn:hud:hmis:owl#FirstName
- Last Name | Text Input | urn:hud:hmis:owl#LastName
- Date of Birth |Date Input | urn:hud:hmis:owl#DOB
- Gender | Dropdown Selection | urn:hud:hmis:owl#Gender

On the form itself:

- If the profile already contains the corresponding value, we will display the value as plain text. 
- If the profile does not contain the value, we will show an input field.
- If the user clicks on a value they've already added, they will be able to edit it.

### Notes

- Date of Birth should be stored as an ISO-8601 date
- Gender is an enumerated list of values. We will store a number from this list in the profile, but we will display a corresponding description to the client:
```
0: Female
1: Male
2: Transgender male to female
3: Transgender female to male
4: Doesn't identify as male, female or transgender
8: don't know
9: Decline to answer
```

**Comment by andycwilliams** [comment]
How many of these fields will we require the user to fill?

**Comment by timbot1789** [comment]
> How many of these fields will we require the user to fill?

None

**Comment by timbot1789** [comment]
@andycwilliams If it's ok with you, I'd like to take this one so I can get the foundations laid for other forms. There's also an issue with the 'gender' field that will need to be worked out (inrupt's libraries don't actually support the kind of enum we're supposed to use for it).

**Comment by andycwilliams** [comment]
> @andycwilliams If it's ok with you, I'd like to take this one so I can get the foundations laid for other forms. There's also an issue with the 'gender' field that will need to be worked out (inrupt's libraries don't actually support the kind of enum we're supposed to use for it).

Sure. I'd only just started anyway. Let me know if I can help down the line.

**Comment by timbot1789** [comment]
Actually, you can still work on it. This is just blocked by this issue:
https://github.com/codeforpdx/PASS/issues/440

I'll take that one, and I'll put up a hook you can use for the form.
