### ISSUE TITLE
Bug: Message badge not updating after message read

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#454]
### Bug Title: Bug: Message badge not updating after message read

---
### Bug Description:

Related to issue #427 and PR #437

At the moment, the badge value for the message remains unchanged even after a message been read.

---
### Reproduction Steps:    
**1.**    Read an unread message
**2.**   See bug

---
### Expected Behavior:

The badge value should decrease each time a message been read. The badge should vanish after all message been read.

---
### Screenshots (If applicable):

https://github.com/codeforpdx/PASS/assets/14917816/b40f199c-e06b-425d-9599-c28ce3ba4b47

---
### Possible Solution (optional):

Have the badge value updated upon refresh or when a message have been read. At the very least, it'll be 1 less than the initial value shown.

**Comment by bingeboy** [comment]
How do you send yourself a message?

**Comment by leekahung** [comment]
> How do you send yourself a message?

You could send a message to yourself by using your own Pod URL as the recipient. But for this example, the pod is https://newtestuser.solidcommunity.net/ (i.e. Alice Alice), so it's from one pod to another instead of to myself.
