### ISSUE TITLE
Bug: Different heading levels used for styling purposes instead of semantically on the home page

### ISSUE THREAD

**Issue by milofultz** [codeforpdx/PASS#456]
### Bug Description:

Heading levels are used in ways to affect their styling and not being used semantically. This leads to poor experiences for users of assistive technologies. See [MDN's notes on navigation using headings](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#navigation).

---

### Reproduction Steps:    

**1.** Go to the home page and turn on your screen reader (Voiceover, in this instance).
**2.** Go to the list of headings (using the rotor in Voiceover)
**3.** Note that they are not linear (e.g. 2, 5, 2, 5; instead of 2, 3, 2, 3)

What should be expected is a linear tree of heading levels. Each child should be a direct descendant of the parent (e.g. an `<h2>` element can only have succeeding `<h3>`s as direct children).

### Screenshots (If applicable):

<img width="1280" alt="Screen Shot 2023-10-13 at 4 55 53 PM" src="https://github.com/codeforpdx/PASS/assets/65684361/98ae602c-e236-49de-9b67-0a96d0ef9ec7">

<img width="1280" alt="Screen Shot 2023-10-13 at 4 55 55 PM" src="https://github.com/codeforpdx/PASS/assets/65684361/590f8b9e-b64b-4d12-820d-aa473b506f37">

<img width="1280" alt="Screen Shot 2023-10-13 at 4 55 57 PM" src="https://github.com/codeforpdx/PASS/assets/65684361/b1d45839-40d2-43d5-82e9-7070379d723f">

<img width="1280" alt="Screen Shot 2023-10-13 at 4 56 00 PM" src="https://github.com/codeforpdx/PASS/assets/65684361/4c02a452-af17-40f6-9229-8150fcc93a40">

Screenshots are from [this extension](https://accessibilityinsights.io/).

### Possible Solution (optional):

Use CSS to style elements using something like a class name or the tag name itself (for example, `.subheader` or applied directly to `h2`) and modify this based on zoom level, width of browser, etc. 

This would likely mean we need to decouple our styling from the MUI `Typography` component. Unsure how this is done, but I see the `sx` prop. 

Thinking it would probably make sense to either make components that are styled correctly that we can then apply a heading level to, or something of that nature, to make a more modular and more easily maintained structure (if these styles are only used in small parts of the app, I don't want to go full design system and build out unnecessary infra).

**Comment by timbot1789** [comment]
Nice catch. You're right that we can override any MUI styles with the `sx` property. If that's not sufficient to fix the accessibility issues, we may want to take a look at [base-ui](https://mui.com/base-ui/getting-started/), which advertises itself as an accessible library.

It looks like, at least for the home screen, the issue is with our own styles. We're hard-coding the `h2` and `h5` values. We can switch those over to more semantic ones pretty easily, and move font sizes to visual CSS styles.

**Comment by xscottxbrownx** [comment]
@milofultz - I completely understand the semantic linear idea, but what I have confusion on is where do you have to start?

Do you always have to start with `<h1>`?


Answers to this and I can get started on this issue.

----

@timbot1789 as well,

MUI makes it much easier to do what we want to do here.  

If you want the text to look stylistically like an `h1`, but need it to be an `h2` semantically:
```js
<Typography variant="h1" component="h2">
  h1. Heading
</Typography>
```

**Comment by milofultz** [comment]
> @milofultz - I completely understand the semantic linear idea, but what I have confusion on is where do you have to start?
> 
> Do you always have to start with `<h1>`?
> 
> Answers to this and I can get started on this issue.

You usually only want a single `h1` on the page. [From MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#avoid_using_multiple_h1_elements_on_one_page):

> While using multiple `<h1>` elements on one page is allowed by the HTML standard (as long as they are not [nested](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#nesting)), this is not considered a best practice. A page should generally have a single `<h1>` element that describes the content of the page (similar to the document's [<title> element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title)).

As far as what needs to be done, it's mainly just ensuring that the headers follow that linear structure. See the [nesting example on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#nesting) as an example of how things should be stacked. 

Another example, think of it as a "belongs to" relationship. 

* We have an `h2` of "Food"
* another heading of "Fruit" would "belong to" the `h2` of "Food", and because it is a direct descendant, it would _have_ to be an `h3`.
* "Apples" would also "belong to" the "Fruit" `h3` and because it is a direct descendant, it would be an `h4`.
* "Vegetables" would be an `h3` because it is the same level as/a sibling of "Fruit" and also a direct descendant of "Food". 
* etc. etc.

Think of them as structural items that help organize the content and you should be gucci 👍

**Comment by xscottxbrownx** [comment]
> > @milofultz - I completely understand the semantic linear idea, but what I have confusion on is where do you have to start?
> > Do you always have to start with `<h1>`?
> > Answers to this and I can get started on this issue.
> 
> You usually only want a single `h1` on the page. [From MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#avoid_using_multiple_h1_elements_on_one_page):
> 
> > While using multiple `<h1>` elements on one page is allowed by the HTML standard (as long as they are not [nested](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#nesting)), this is not considered a best practice. A page should generally have a single `<h1>` element that describes the content of the page (similar to the document's [<title> element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title)).
> 
> As far as what needs to be done, it's mainly just ensuring that the headers follow that linear structure. See the [nesting example on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#nesting) as an example of how things should be stacked.
> 
> Another example, think of it as a "belongs to" relationship.
> 
> * We have an `h2` of "Food"
> * another heading of "Fruit" would "belong to" the `h2` of "Food", and because it is a direct descendant, it would _have_ to be an `h3`.
> * "Apples" would also "belong to" the "Fruit" `h3` and because it is a direct descendant, it would be an `h4`.
> * "Vegetables" would be an `h3` because it is the same level as/a sibling of "Fruit" and also a direct descendant of "Food".
> * etc. etc.
> 
> Think of them as structural items that help organize the content and you should be gucci 👍

understand all this completely. What I am asking is if an h1 HAS to be on every page, or can you start from any header level (like h2 or h3 for example) and work down linearly?

**Comment by xscottxbrownx** [comment]
> understand all this completely. What I am asking is if an h1 HAS to be on every page, or can you start from any header level (like h2 or h3 for example) and work down linearly?

Found it in `usage notes`, yes start from `h1`

**Comment by milofultz** [comment]
Ah @xscottxbrownx , not trying to mansplain at you, my apologies. Let me know if you have any more questions

**Comment by xscottxbrownx** [comment]
@milofultz have one more question for you...

Do you have any suggestions for pages that don't logically have an `h1`?  Like for instance our `Contacts` page, or this `Home` page?   The docs say to always start from an `h1`.

**Comment by milofultz** [comment]
@xscottxbrownx There should always be an `h1` for assistive technologies to have the proper hierarchy and know the content, but this `h1` can be made invisible so it's only for assistive technologies. It should identify and describe the main content of the page. For "Home" and possibly for "Contacts", I'd reckon it's probably the same as the `title` of the page? For the case of "Contacts", an `h1` of "Contacts" would probably suffice, or more if context is needed.

See [this page for an example](https://accessibleweb.com/question-answer/does-the-tag-on-a-page-need-to-be-visible-to-the-eye-and-to-screen-readers/):

> Should an `<h1>` tag be used in this manner, it should be written in HTML before the main content of the page. Screen reader users can utilize the level one heading as a means to skip to the page header (similar to how a skip to content link navigates to the main content of the page). The `<h1>` tag should not be hidden from the [accessibility tree](https://accessibleweb.com/question-answer/what-is-an-accessibility-tree-and-how-do-i-view-it/), as it provides guidance and assistance to those who use screen readers and other assistive technology to understand the contents of the page.

So no need to `aria-hidden` or `role="presentation"` or anything. But you can make it visually hidden through various means of CSS, like the following I got from [WebAIM's recommendation](https://webaim.org/techniques/css/invisiblecontent/#offscreen):

```css
.sr-only {
  position:absolute;
  left:-10000px; 
  top:auto;
  width:1px;
  height:1px;
  overflow:hidden;
}
```

> The `.sr-only` CSS class ("sr-only" meaning "screen reader only", though the class name does not really matter) should then be referenced from within the tag of the element being hidden ... Sighted users will not see the hidden content at all—it will be hidden well to the left of the visible browser window. Because it is still part of the page content, screen readers will read it.

**Comment by xscottxbrownx** [comment]
@milofultz could you Friend request on Discord, to make this convo a little easier? I've got just a couple ideas to run by you - thinking about this for all the pages.

**Comment by milofultz** [comment]
Hey @xscottxbrownx , I thought I friended you on Discord, but now I'm not so sure 🙃 . What is your username? You can shoot me a message too at `@milofultz`

**Comment by xscottxbrownx** [comment]
> Hey @xscottxbrownx , I thought I friended you on Discord, but now I'm not so sure 🙃 . What is your username? You can shoot me a message too at `@milofultz`

Found you and sent message - username: veganedge

**Comment by milofultz** [comment]
Going through this again and noticing that some headings were downgraded to just `strong` tags, but they are definitely headings in that they "[reflect the organization of the content](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#nesting)" (Secure Storage, etc.).

<img width="938" alt="Screen Shot 2023-11-12 at 10 03 34 AM" src="https://github.com/codeforpdx/PASS/assets/65684361/62de3543-b203-4fb4-a83c-62d5a740d8cb">
