### ISSUE TITLE
Enhancement:  "Remove Profile Image" user experience optimization

### ISSUE THREAD

**Issue by Jared-Krajewski** [codeforpdx/PASS#463]
### Describe the Current Behavior/Feature:
The "Remove Image" button on the Profile page uses default window prompt instead of a modal in project style. 

https://github.com/codeforpdx/PASS/assets/37914436/0ba44ff5-8d59-4e6f-9aad-b3830a24a6ca

### Proposed Behavior/Feature:
Add a modal similar to delete contact with 'cancel' and 'delete' options

### Rationale:
This should improve the user experience of editing their profile image, and make the UI more consistent.

**Comment by leekahung** [comment]
This should not be a modal. It should be an independent page clients could use to create their first Pod after the case manager gave them the link via a phone message or via email.

**Comment by JonnyMc94** [comment]
Hi @Jared-Krajewski, I would like to work on this issue if possible. Could you assign it to me?

**Comment by TheChunkyPumpkinhead** [comment]
@JonnyMc94, Howzit. This is already assigned to someone.

**Comment by andycwilliams** [comment]
@TheChunkyPumpkinhead I saw you unassigned yourself from the PR. Does this mean you wish to do so for this issue as well?
