### ISSUE TITLE
Organization to User Communication

### ISSUE THREAD

**Issue by GoodGuyGregory** [codeforpdx/PASS#49]
In Order to initiate the initial communication process for sending and recieving documetation. a process must initiated to allow this communication. Basically think like a friend request with a note.

**Comment by leekahung** [comment]
A kind of message system is being developed at the moment which uses TTL files being send to another user's Solid Pod and converted back into JSON in PASS (see PR #148). A full system is still being build, will leave this issue open until completion.

**Comment by leekahung** [comment]
Don't necessarily have organization to user communication yet, but we do have user-to-user via the new message system in place with PR #148. Users can compose new messages to each other, but we have yet to establish a "reply" functionality from the inbox (see Issue #226).

**Comment by leekahung** [comment]
PASS now has a message system in place with a reply system in the works. Think we can close this issue for now. Additional features for notification could be discussed in the future.
