### ISSUE TITLE
[Enhancement] - Styling Update for InactivityMessage.jsx

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#492]
### Describe the Current Behavior/Feature:

At the moment, most of our modals has been converted/"standardized" to use the following style, rounded buttons with the modal action matching the title on the right button:

![Screen Shot 2023-11-05 at 19 35 27](https://github.com/codeforpdx/PASS/assets/14917816/8146ee21-98ec-487f-867c-acc13882382c)

![Screen Shot 2023-11-05 at 19 35 41](https://github.com/codeforpdx/PASS/assets/14917816/7e62f08a-8cd3-4da9-8087-2862f5ad617c)

However, one component has yet to be updated, `InactivityMessage.jsx`:

![Screen Shot 2023-11-05 at 19 33 43](https://github.com/codeforpdx/PASS/assets/14917816/2c19a7ce-fa2f-4c1b-a4cd-52cf83c17fe7)

### Proposed Behavior/Feature:

We can update the styling of `InactivityMessage.jsx`, so that it'll be consistent with the other modals.

**Comment by JonnyMc94** [comment]
Hi @leekahung, I would like to work on this. Could you assign it to me?
