### ISSUE TITLE
Enhancement: Update landing page

### ISSUE THREAD

**Issue by Jared-Krajewski** [codeforpdx/PASS#499]
### Describe the Current Behavior/Feature:
replace logo with pass logo (found in readme and wiki) Add H1 with PASS & tagline in top of body. Take feature sections with pictures and separate into cards/sections. Further information can be requested from @Jared-Krajewski  @ogorman89 

### Rationale:

Website brand/identity can be a bit ambiguous, so someone could be confused by what they are using.

**Comment by rohit-chaware** [comment]
@Jared-Krajewski, I would like to work on this enhancement.

**Comment by xscottxbrownx** [comment]
Sorry, this is the approach I am taking to solve #456 - therefore both issues will be solved. I didn't realize this was a separate issue or else I would have assigned it to myself earlier.

**Comment by leekahung** [comment]
> Sorry, this is the approach I am taking to solve #456 - therefore both issues will be solved. I didn't realize this was a separate issue or else I would have assigned it to myself earlier.

Ah, it's okay. Didn't realize it either. I'll close this issue as a duplicate then. I'll refer people to the more detailed issue on #456.
