### ISSUE TITLE
Bug: mobile "sign in" modal side scroll

### ISSUE THREAD

**Issue by Jared-Krajewski** [codeforpdx/PASS#500]
### Bug Description:

The mobile sign-in button needs styling to match desktop 'login' button (the text stays as "sign in" to keep button distinct from the login button). 

On top of that, the modal has side to side scroll, so the input field within the modal needs styling adjustments for mobile (at least down to 280px). (see screenshot below)

### Screenshots (If applicable):

<img width="192" alt="Screenshot 2023-11-07 at 7 13 07 PM" src="https://github.com/codeforpdx/PASS/assets/114430929/560a54a4-9890-4fee-8171-95c70f6fa453">

<img width="206" alt="Screenshot 2023-11-07 at 7 13 13 PM" src="https://github.com/codeforpdx/PASS/assets/114430929/7cbc521d-2acf-4623-9879-de729a1d2836">

### Possible Solution (optional):

Update MUI styling for the sign in button and adjust the styling for the element with the input field to fit within the modal. The font size within that field could be adjusted, if needed.

**Comment by khoadangtran** [comment]
Hey, I want to work on this issue, Can you please assign it to me
