### ISSUE TITLE
Bug: Nav bar Hamburger menu and notification bell improvements

### ISSUE THREAD

**Issue by Jared-Krajewski** [codeforpdx/PASS#501]
### Bug Description:

1. Hamburger menu and bell from nav bar has a green backdrop others have a black opacity. All backdrop colors when modals appear should be uniform

2. menus appear slightly overlapping nav, should start at bottom of nav bar.

3. Text is staggered and icons are different sizes.  (probably because icons are different sizes)

4. Add padding around divider separating settings and log out below routes.

### Screenshots (If applicable):

<img width="159" alt="Screenshot 2023-11-07 at 7 35 43 PM" 
src="https://github.com/codeforpdx/PASS/assets/114430929/2aec5aaa-f119-422f-9766-d37d03c93f9f">

### Possible Solution (optional):

Update existing styling for existing nav menus from MUI such that it removes the excess padding, make nav menu icons consistent, make nav menu appear below navbar instead of the element it's attached to, and update the backdrop color to match the black backdrop of modals when they're opened.

**Comment by Pooja1672** [comment]
Hi @Jared-Krajewski , I would like to work on this issue. Can you please assign this issue to me?

**Comment by khoib2014990** [comment]
Hey, I want to work on this issue, Can you  assign it to me.

**Comment by richestrinh** [comment]
Hi, would I be able to work on this?

**Comment by amandaguan-ag** [comment]
@Jared-Krajewski The hamburger menu does not exist in current UI

**Comment by Jared-Krajewski** [comment]
> @Jared-Krajewski The hamburger menu does not exist in current UI

Just checked latest from dev branch, its there.  Not sure why its not appearing for you. Also it appears @richestrinh has a branch and is close to merging the fixes in to close this issue.
