### ISSUE TITLE
Enhancement: Add mobile cards view to profile document list

### ISSUE THREAD

**Issue by Jared-Krajewski** [codeforpdx/PASS#502]
### Describe the Current Behavior/Feature:

After the Table (see screenshot below of existing design) gets converted into an MUI data grid, we'll probably want a better mobile view experience for the document list.

<img width="650" alt="Screenshot 2023-11-07 at 7 46 08 PM" src="https://github.com/codeforpdx/PASS/assets/114430929/73d66a15-d08b-4500-be91-d63280644e00">

For a while, a card design has been under discussion, see screenshot from Issue #222 (which was for `contactsList`, formerly `clientList`). However, the designs has yet to be implemented.

<img width="831" alt="Screenshot 2023-08-23 at 1 28 42 PM" src="https://github.com/codeforpdx/PASS/assets/71395931/a4cb4afd-e376-4c7c-a370-d7ae27cdd218">

For the responsive breakpoint we could use the existing MUI breakpoint at `theme.breakpoints.down('sm')` which can be obtained by importing theme and calling `const isSmallScreen = useMediaQuery(theme.breakpoints.down('sm'));`.

### Rationale:

While MUI data grids might look great for Desktop, it might be better to adopt a card design instead for mobile, even if it lack some of the features like sorting and filtering. But, we could always create a custom function for sorting and filtering for those cards in the future, if needed.

**Comment by leekahung** [comment]
Duplicate issue. Updated issue in #606.
