### ISSUE TITLE
Enhancement: Button consistency to pill shape

### ISSUE THREAD

**Issue by Jared-Krajewski** [codeforpdx/PASS#503]
### Describe the Current Behavior/Feature:

Design-wise, the UX team was moving forward with buttons being "pill"-shaped. There are certain places where buttons remains rectangular boxes, such as the buttons within the user profile and the sign-in button.

### Rationale:

Keep things consistent with existing designs for the website.

### Proposed Implementation (if applicable):

The existing `border-radius` for most buttons utilizes a value of `20px`. Think we could have this implemented for any non-compliant button.

**Comment by Pooja1672** [comment]
Hi @Jared-Krajewski , I would like to work on this issue. Can you assign this to me?
