### ISSUE TITLE
Bug: Modal buttons in different orders, consistency update

### ISSUE THREAD

**Issue by Jared-Krajewski** [codeforpdx/PASS#504]
### Bug Description:

For consistency: 
Cancel buttons should be on top with action on the bottom. if side by side cancel on left and action on right. 
This affects share icons. (see screenshots below)

### Screenshots (If applicable):

<img width="179" alt="Screenshot 2023-11-07 at 7 55 55 PM" src="https://github.com/codeforpdx/PASS/assets/114430929/504479cb-42a5-4d57-a95d-60f1fe2df7c3">

<img width="364" alt="Screenshot 2023-11-07 at 7 56 29 PM" src="https://github.com/codeforpdx/PASS/assets/114430929/72979504-2d5c-4a34-aff9-97154bd724b4">

### Possible Solution (optional):

Update components related to affected modals, both related to document sharing.

**Comment by Pooja1672** [comment]
HI @Jared-Krajewski , I would like to work on this issue. Can you assign this to me?

**Comment by khoadangtran** [comment]
Hey, I want to work on this issue, Can you please assign it to me?

**Comment by amandaguan-ag** [comment]
@Jared-Krajewski  Solved with pr #538 , could you help to review? Thank you.
