### ISSUE TITLE
Enhancement: "Skip Navigation" links should be available to skip repetitive content

### ISSUE THREAD

**Issue by milofultz** [codeforpdx/PASS#511]
### Describe the Current Behavior/Feature:

n/a

### Proposed Behavior/Feature:

Skip link for users of assistive technologies to skip past repetitive content.

### Rationale:

Keyboard users often have to move past the same things on every page (navigation links, etc.) to get to the main content. Skip links lets a keyboard user skip past those repetitive elements and get to the main content. 

See [WebAIM's article](https://webaim.org/techniques/skipnav/) for more details. You can also see an example of it on their page; on refresh, press tab and you'll see a skip link appear and disappear when you tab again.

<img width="1392" alt="Screen Shot 2023-11-12 at 10 20 48 AM" src="https://github.com/codeforpdx/PASS/assets/65684361/05108ed1-1fe7-41c4-b0a2-d44d585c63e1">

### Proposed Implementation (if applicable):

One that is not visible until you tab is common and well vetted. See [WebAIM's article](https://webaim.org/techniques/skipnav/) for more details.

**Comment by bingeboy** [comment]
I'll take this one.
