### ISSUE TITLE
Enhancement: Civic Profile - Housing Information Form

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#513]
### Describe the Current Behavior/Feature:
We are currently building out a Civic profile to use with civic services.

### Proposed Behavior/Feature:
Part of this profile should contain information on a person's housing situation. Where did they live last? How secure is their housing, etc? 

### Proposed Implementation (if applicable):
Add the following fields to the `civic_profile.ttl` data store and add a UI to the Civic Profile page to edit them:

- `urn:hud:hmis:owl#LastPermanentCity`: The city component of their last permanent address
- `urn:hud:hmis:owl#LastPermanentState`: The state component of their last permanent address
- `urn:hud:hmis:owl#LastPermanentStreet`: The street component of their last permanent address
- `urn:hud:hmis:owl#LastPermanentZIP`: The ZIP code of their last permanent address
- `urn:hud:hmis:owl#MonthsHomelessPast3Years`: An enum describing how long they've been homeless in the past 3 years
    - 101: 1 month
    - 102: 2 months
    - 103: 3 months
    - 104: 4 months
    - 105: 5 months
    - 106: 6 months
    - 107: 7 months
    - 108: 8 months
    - 109: 9 months
    - 110: 10 months
    - 111: 11 months
    - 112: 12 months
    - 113: more than 12 months
- `urn:hud:hmis:owl#TimesHomelessPast3Years`: An enum describing how many times they have lost their housing in the past 3 years
    - 1: 1 time
    - 2: 2 times
    - 3: 3 times
    - 4: 4 or more times 
- `urn:hud:hmis:owl#TimeToHousingLoss`: Enum describing how long until they will become homeless
    - 0: 0-6 days
    - 1: 1-7 days
    - 2: 14-21 days
    - 3: More than 21 days    

### Additional context:
It may be worthwhile to to map or prepopulate some of these values (e.g. address) from similar values found in other public profiles in a client's pod.

**Comment by timbot1789** [comment]
This ticket was partially completed in this PR:
https://github.com/codeforpdx/PASS/pull/515

It implemented the data model, and added part of the UI. What remains is UI implementations for the following fields:
- urn:hud:hmis:owl#MonthsHomelessPast3Years
- urn:hud:hmis:owl#TimesHomelessPast3Years
- urn:hud:hmis:owl#TimeToHousingLoss

These 3 are all enums, and should be represented as [&lt;select> element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) or an MUI equivalent.

The options for the select element are in the description.  The values on the left of the colon MUST be the values stored in the profile. The values on the right are the labels to show to the user. You may change these if you think of a better wording.

**Comment by faddah** [comment]
Filed PR on this, #633 - 513 enhancement civic profile housing information form.

**Comment by andycwilliams** [comment]
Issues should not be closed until the related PR has been fully merged.
