### ISSUE TITLE
Bug: (Contacts) "No contacts found" using `h2` for content instead of organization

### ISSUE THREAD

**Issue by milofultz** [codeforpdx/PASS#518]
### Bug Description:

When no contacts are found, the main content ("No contacts found") uses an `h2` instead of something more semantically appropriate. Headings should be used for navigation, not for content.

### Reproduction Steps:    

**1.** Log in to an account that has no contacts.
**2.** Go to the Contacts tab.
**3.** Observe the DOM of the content ("No contacts found").

### Expected Behavior:

The content should be something like a `p` tag or similar.

### Screenshots (If applicable):

<img width="1392" alt="The Contacts tab of a logged in user, showing 'No contacts found' prominently in the center." src="https://github.com/codeforpdx/PASS/assets/65684361/91d2279e-8e1f-4894-9666-cb2de92e07e5">

### Additional Context (optional):

* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#navigation

### Possible Solution (optional):

* Make the heading above the list of contacts an actual `h2` element. For navigation with assistive technology, this will show someone "this is where the contacts are/will be"; when they go there, they will find that there are no contacts available. This will give a consistent experience regardless if contacts exist or not.
* Change the element for the text to something that is meant for dynamic content, like a `p` tag.

**Comment by milofultz** [comment]
This is found in the `EmptyListNotifications` component

**Comment by milofultz** [comment]
Actually, when contacts _do_ exist, we have a header that is coded as a `p` tag, too. So this fix should also include refactoring that out

<img width="1392" alt="Screen Shot 2023-11-14 at 7 59 34 PM" src="https://github.com/codeforpdx/PASS/assets/65684361/b3aeafd1-ee3a-4a69-8aa4-9dd3ef1e6b55">

**Comment by JonnyMc94** [comment]
Hi @milofultz, I would like to work on this if you could assign it to me please?
