### ISSUE TITLE
Enhancement: Allow editing of Contacts

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#571]
### Describe the Current Behavior/Feature:
Currently, a user is able to create, read, and delete a contact. But they are not able to easily edit an existing contact.

### Proposed Behavior/Feature:
Add a way for users to edit the entries in their contacts list. This can be a button in the row of the contacts table with the [MUI edit icon](https://mui.com/material-ui/material-icons/?query=edit&selected=Edit). This button can then launch "Create Contact" modal with the title changed to "Update Contact." We can use this modal to modify the first name, last name, and web ID of an entry in the contact list.

### Additional Context
Since the Web ID is the identifier for the object, updating the web ID will likely require deleting the old contact entry, and then creating a new contact entry.

**Comment by ofu997** [comment]
I can attempt this

**Comment by andycwilliams** [comment]
@JaeGif Hoping to check in and see how this is going

**Comment by JaeGif** [comment]
@andycwilliams hey, I've put this one on the backburner for now as I'm a few rounds deep interviewing for a full time role. 

I'm hoping to have time this weekend to get to it, but if it's important to be done sooner I can publish my branch and hand it off.

**Comment by andycwilliams** [comment]
@JaeGif This is one of the issues remaining before we launch MVP so sooner than later is ideal.

**Comment by JaeGif** [comment]
> @JaeGif This is one of the issues remaining before we launch MVP so sooner than later is ideal.

Alright, I've pushed the most recent changes to this [branch](https://github.com/codeforpdx/PASS/tree/571/edit-contacts).

I believe I've got the editing functionality down. If it needs some minor changes I can do that but if it needs anything major I'll probably have to hand it off. I'll make a PR for it now.
