### ISSUE TITLE
Enhancement: Remove Username from contacts, update required fields

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#572]
### Describe the Current Behavior/Feature:
Currently we have a field, username, that we require for every contact list added. This is a holdover from an early iteration of PASS, and isn't needed. Today it confuses more than it helps. We also currently require a first name and last name when creating a contact.

### Proposed Behavior/Feature:
Remove the username field from PASS contacts, and make the first name and last name no longer required. The username is a concept that is not particularly applicable to Solid. People are identified by Web IDs, not usernames. The Web ID is what we need to record.

We also don't need to enforce the first name or last name. As long as the person has the web ID, they can create a contact. If they don't have the web ID, they can't create the contact - the logic we have around the contact entry won't run without it. So we can remove those required fields. They're useful, but not necessary.

The new fields on Contacts should be:

- Web ID: required
- First Name: optional
- Last Name: optional

### Rationale:
We want to keep PASS simple. Adding multiple different kinds of identifiers like username and webId to the system confuses more than it helps.

**Comment by fighawkins** [comment]
i'll try to knock this out tomorrow morning/afternoon.
