### ISSUE TITLE
Enhancement: Update document sharing modal to pull from contacts list

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#573]
### Describe the Current Behavior/Feature:
Currently, to share a document with someone, you must enter their pod URL. This is hard for users because it requires them to remember the Pod URL of everyone they want to share with. Conceptually it is incorrect as well, because you do not share with a pod, you share with a Web ID 
![image](https://github.com/codeforpdx/PASS/assets/37914436/ed069c42-870c-40f5-b896-a45730a0b1a1)

### Proposed Behavior/Feature:
Rework the sharing modal to share with people off their contact list. This can use the same functionality as currently exists in the messaging system (a dropdown that searches the contact's first and last name).
![image](https://github.com/codeforpdx/PASS/assets/37914436/0d9e481e-239f-4e9d-9948-dbcd5d24c91e)

### Additional context:
This may require removing logic around adapting the "pod url." This logic is unnecessary. If we have a person's web Id, we can use it directly.

**Comment by bingeboy** [comment]
@leekahung I've been tied up with other obligations so I've unassigned this ticket. Hopefully, I'll have time to code again soon.

**Comment by timbot1789** [comment]
No worries. Thanks for letting us know @bingeboy

**Comment by leekahung** [comment]
> @leekahung I've been tied up with other obligations so I've unassigned this ticket. Hopefully, I'll have time to code again soon. 

All good, thanks for your contributions up to now!

**Comment by joshua-cornett** [comment]
I believe I've finished implementing webID sharing in place of podURLs as well as a contacts/webIDs dropdown. I'm not seeing how document sharing is tested, though, to include when I stash my changes to cross-reference the original state. Obviously I want to confirm this works before I try to merge and close 😅. How should I be testing it?
