### ISSUE TITLE
[Enhancement] - Refactor copy functionality as a reusable function

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#582]
### Describe the Current Behavior/Feature:

With our latest changes in Development, we now have a function that lets users copy long URLs associated with webIds and invite links. Given that it might be a function that could be used in other places outside of the Profile page, think it'll be a good idea to make it a reusable function.

### Rationale:

Makes copy functionality reusable across the app.

### Proposed Changes:

Store the clipboard and addNotification functions together as one function in perhaps utils and make it export from there.

**Comment by andycwilliams** [comment]
Unassigning myself as this is a good issue for newer contributors

**Comment by andycwilliams** [comment]
Never mind I'll just finish it lol
