### ISSUE TITLE
[Enhancement] - Restyle Sign-in component

### ISSUE THREAD

**Issue by fighawkins** [codeforpdx/PASS#587]
### Describe the Current Behavior/Feature:
I noticed the sign in component on the /signup page is quite UGLY. just kidding, but I think it could looks a bit better.
<img width="746" alt="Screenshot 2024-02-28 at 7 36 10 PM" src="https://github.com/codeforpdx/PASS/assets/143238486/963bb26f-3c58-4b67-8a8e-e2066e15d961">

### Proposed Changes:
Detail the changes you propose to make to the existing feature. Include:
Perhaps remove one card, make it all on one. make elements balanced. make card have even margins and padding on top and bottom. just make it look pretty.

### Rationale:
How does it improve the current functionality? Discuss any limitations or problems with the existing feature that your suggestion aims to resolve.
It currently comes across as a bit amateur, so it effects user experience by seeming untrustworthy.

### Possible Drawbacks:
Discuss any potential drawbacks or negative impacts this enhancement might have, including:
no drawbacks.

### Alternatives Considered:
Mention any alternative solutions or enhancements you've considered. Why were they not chosen or why are they less desirable than your proposal?

### Additional Context:
Add any other context or screenshots about the enhancement request here.

**Comment by timbot1789** [comment]
The purpose of the current design is to later support an additional card that allows people to sign up with an existing pod[^1]. In that design, the Register for PASS paper would have 2 cards: Create a new pod OR sign up with an existing pod. There's a stub issue for [this here](https://github.com/codeforpdx/PASS/issues/586).

Any restyling of this page should be able to be extended in such a way.

[^1]: The first version of this page actually had both flows, but the second "signup with an existing pod" was really buggy, so we removed it and haven't put it back yet.

**Comment by AJSterner** [comment]
Updated with a tab based design allowing the user to select between the two sign in flows, however I'm having some trouble with the navbar overflowing and moving things around when we switch to the "existing pod" flow.

Any ideas of how to handle this? It significantly shifts the sign in paper...

![new_pod](https://github.com/codeforpdx/PASS/assets/16945988/1a6545c9-11e4-4359-8a4e-3e31782de308)
![overflow](https://github.com/codeforpdx/PASS/assets/16945988/d82cfb57-7595-4813-88a3-d0905a737e1c)

**Comment by AJSterner** [comment]
Mobile view! Still needs some cleanup.
![existing_pod_mobile](https://github.com/codeforpdx/PASS/assets/16945988/c113c96c-2e0c-49e0-bcd4-57988455d8a8)
![new_pod_mobile](https://github.com/codeforpdx/PASS/assets/16945988/82fc813b-d596-43d8-a4a7-85ceee2c2dc7)
