### ISSUE TITLE
[Bug Report] - Add Contact Validation

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#614]
### Describe the bug:

Currently, validation for the `Add Contact` modal seems to be broken (see screenshot below). When clicking on "Add Contact", without the username for the new contact to be added, it breaks down and get stuck on the modal with the function for `onSubmit` getting triggered.

While users can escape with the cancel button or ESC key, the "Add Contact" button is no longer accessible.

### Expected behavior:

Form validation requires users to have a valid username before it can submit the form for "Add Contact".

### Screenshots:

<img width="1512" alt="Screenshot 2024-04-16 at 6 30 46 PM" src="https://github.com/codeforpdx/PASS/assets/14917816/3b34a230-e241-40d8-bb06-48523247a5d9">

### To Reproduce:
1. Go to Contacts
2. Click on "Add Contacts"
3. Insert information only in the optional fields
4. Click on "Add Contact" button
5. See error

### Possible Fix:

Include validation as part of the input field for username.

**Comment by JaeGif** [comment]
Do we want the other fields not labeled "optional" to be mandatory?

**Comment by leekahung** [comment]
Yeah, it would be good to keep fields that are not optional as required fields for submission.
