### ISSUE TITLE
[Enhancement] - Make "Continue session?" popup and Upload Document modal more responsive

### ISSUE THREAD

**Issue by andycwilliams** [codeforpdx/PASS#621]
### Describe the Current Behavior/Feature:

After a period of inactivity, the user is prompted with a "Continue session?" popup. However, it is not optimized for mobile views. Namely, the buttons should be arranged vertically rather than horizontally on small screens.

<img width="278" alt="2024-04-25 (15)" src="https://github.com/codeforpdx/PASS/assets/83156697/b8ecdfc2-4ca4-4ac4-8d96-72d94dcabfe2">

The same is true for the Upload Document modal.

<img width="275" alt="2024-04-26 (16)" src="https://github.com/codeforpdx/PASS/assets/83156697/49a18cdd-d90e-4e6b-85ed-52d3fb6404fb">

### Rationale:

By not being more responsive, we make the UI visually crammed as well as inconsistent with our theming elsewhere. For example, see the New Message modal:

<img width="274" alt="2024-04-25 (11)" src="https://github.com/codeforpdx/PASS/assets/83156697/a5c162d7-68b3-49a3-b12f-72c53418adf5">

### Proposed Changes:

Using Material UI, refactor the buttons to match styling in other modals (aka negative action on top, positive action on bottom). In this case, the Log Out button should appear above the Continue button.

In the case of the Upload Document modal, the Cancel and Upload buttons are properly arranged, yet the Choose File and Use Webcam ones are not.

**Comment by richestrinh** [comment]
I'll give this a try :)

**Comment by andycwilliams** [comment]
> I'll give this a try :)

Thanks for your interest!

This issue will likely now be resolved by #632. Apologies if you've already put in a lot of time into this.
