### ISSUE TITLE
[Enhancement] - Fix NewMessageModal width changes

### ISSUE THREAD

**Issue by andycwilliams** [codeforpdx/PASS#639]
### Describe the Current Behavior/Feature:

Despite all modals being subject to the set width, `NewMessageModal` reacts to them strangely.

<img width="395" alt="2024-05-22 (5)" src="https://github.com/codeforpdx/PASS/assets/83156697/0ac802a4-329d-4759-bce8-0bfb26eef1e1">
<img width="388" alt="2024-05-22 (4)" src="https://github.com/codeforpdx/PASS/assets/83156697/d6d994db-e466-43f2-9de8-0b884addf663">

### Rationale:

It has to do with the `oldMessage` conditional that converts the modal from a new message into a reply. Specifically with how that conditional is being implemented on around line 183 with the `previousMessage` TextField.

### Proposed Changes:

Reply To is properly formatted the way all the other modals are. It's just New Message that squashes the content.

Ensure the modal retains the preferred formatting in both conditions.

**Comment by andycwilliams** [comment]
@ofu997 This could be a separate issue, but if you're willing, could you disable the Submit button until the required fields are filled? We already do this with Add Contact and Upload Document, so it should be pretty simple to just copy from those.

Totally fine if not. It's outside this specific scope and I can leave it for another issue. Just thought it might save a bit of time doing it at the same time.

**Comment by ofu997** [comment]
@andycwilliams 
The issue seems to be that the number of inputs affects how wide the input group is. 

![Screenshot 2024-05-31 161818](https://github.com/codeforpdx/PASS/assets/22952319/594aa3a6-be07-446f-9245-3d39c4003f4e)
![Screenshot 2024-05-31 161717](https://github.com/codeforpdx/PASS/assets/22952319/5bcd43b5-7bab-4467-a224-e6ffb75a6035)

**Comment by andycwilliams** [comment]
@ofu997 How annoying. I haven't experimented with it much but one possible workaround is shortening the width from '600px' down to '475px'. Not the ideal solution, though.

**Comment by andycwilliams** [comment]
Decided to remove the MVP label since, though annoying, does not interfere enough to be the highest priority.

We definitely still want to find out what's causing this and address it, though.

**Comment by ofu997** [comment]
ok. Didn't touch this issue in June. Will try again.
