### ISSUE TITLE
[Bug Report] - Mismatching passwords not shown on pod creation

### ISSUE THREAD

**Issue by AJSterner** [codeforpdx/PASS#650]
### Describe the bug:
The user is required to confirm their password when creating a new account, however the password in "Confirm Password" is not checked against the "Password" field. You can create a new account with mismatching passwords (Password, Confirm Password).

### Expected behavior:
I would expect client side validation to block submission until the passwords match.

### Actual Behavior:
You can successfully create an account with mismatching password (the primary?)

### Screenshots:
This would work:
![image](https://github.com/codeforpdx/PASS/assets/16945988/9b52522c-e63b-4a58-af3a-90196afa22d2)

### To Reproduce:
1. Go to /signup
2. Attempt to create an account with different passwords 
3. ...
4. Success?

### Possible Fix:
We should block submission and show an error, additionally password strength validation (length etc.) seems to be missing as well.

**Comment by andycwilliams** [comment]
Bitwarden 🙌

**Comment by leekahung** [comment]
Hey @AJSterner was curious if you're still doing this bug fix? I could start up a branch and get this patched up. 👍
