### ISSUE TITLE
Reroute Civic Profile and disable Financial Info form

### ISSUE THREAD

**Issue by andycwilliams** [codeforpdx/PASS#651]
### Describe the Current Behavior/Feature:

The first issue is that the Civic Profile landing page does not contain anything to distinguish it as its own page:

<img width="799" alt="2024-06-04 (2)" src="https://github.com/codeforpdx/PASS/assets/83156697/7514ee4e-c017-4c80-b3e3-ab07d3d790cc">

So there's little reason for the user to be directed to that page. 

Secondly, as opposed to the other forms in the Civic Profile, the functionality for Financial Info is not in place. As a result, it is empty:
<img width="801" alt="2024-06-04 (3)" src="https://github.com/codeforpdx/PASS/assets/83156697/0c997511-aa01-460a-8d8a-103c0a77f3e1">

### Rationale:

As we move towards MVP, we have to trim (if temporarily) any features that we don't expect to be fully ready in time.

Directing the user to the Civic Profile landing page right not just makes them perform an extra click to access any of the functionality (aka the two forms). It would be a bit more intuitive to just direct them to the Basic Information form itself.

As for the Financial Information form, the Basic and Housing forms cover all of the form functionality currently written. Thus Financial Information has no use at this time.

### Proposed Changes:

- [x] Reroute the "Civic Profile" link in the Navbar so that it lands on the Basic Info form rather than the empty parent page.
- [x] Disable (but do not remove) the link to the Financial Info form.
- [x] Comment out the unused code rather than delete it, since these may be implemented in the future.

### Additional Context:

These tasks may be simpler if #634 were to be done first but it is not necessary.

**Comment by sarthakChauhan12** [comment]
Can I work on this issue?
