### ISSUE TITLE
[Bug Report] - Fix Failing Tests

### ISSUE THREAD

**Issue by andycwilliams** [codeforpdx/PASS#662]
Work on this can begin right away. However, it should not be submitted until ensuring there are no additional failing tests from #571 and #606.

Component tests to fix:

- [x] BasicInfo.test.jsx - Andrew
- [x] ContactListTable.test.jsx
- [x] ContactListTableDesktop.test.jsx - Andy
- [x] ContactListTableMobile.test.jsx - Andy
- [x] DocumentCard.jsx - Josh
- [x] DocumentsDesktop.jsx - Josh
- [x] DocumentsMobile.jsx - Josh
- [x] HousingInfo.test.jsx - Andrew
- [x] Messages.test.jsx - Andy
- [x] PodRegistrationForm.test.jsx
- [x] Profile.test.jsx - Andrew
- [x] Signup.test.jsx

### Describe the bug:

Some of the tests are now failing.

### Expected behavior:

Every test should pass to ensure maximum test coverage possible.

### To Reproduce:

1. Run `npm run test` in the terminal

### Additional context:

The tests fail due to changes in the related components. So they should be updated or, when relevant, rewritten according to each component's new specifications. For example, some have been broken up into multiple smaller components and so will need additional tests.

`CivicProfile` and `FinancialInfo` are not yet implemented and therefore do not require tests at this time

**Comment by andycwilliams** [comment]
I've written a few of the tests now but would appreciate some assistance so we can get this done sooner rather than later. I'm not the quickest at these.

**Comment by AJSterner** [comment]
I'm fairly sure a bunch of these are timeouts which can be fixed by bumping up the global test timeout time or on a per-test basis.

**Comment by AJSterner** [comment]
@andycwilliams I may have accidentally fixed them all on #666, take a look.

**Comment by AJSterner** [comment]
@andycwilliams I don't see any obvious problems with BasicInfo or HousingInfo so I checked them off. Please let me know if there are others you'd like picked up (Profile?).

**Comment by AJSterner** [comment]
Added my name next to Profile.

**Comment by andycwilliams** [comment]
Several more tests have been written as of #667. Only a handful more to go.

**Comment by andycwilliams** [comment]
@AJSterner Any news on tests for Profile? I'm aiming to get MVP wrapped up soon as possible.

**Comment by AJSterner** [comment]
@andycwilliams Profile tests ready for an initial review:
https://github.com/codeforpdx/PASS/pull/673

**Comment by AJSterner** [comment]
Closed out Profile tests!
