### ISSUE TITLE
[Bug Report] - refresh in vercel causes 404 (react router)

### ISSUE THREAD

**Issue by Jared-Krajewski** [codeforpdx/PASS#676]
### Describe the bug:
A clear and concise description of what the bug is including error messages.

### Expected behavior:
page should refresh

### Actual Behavior:
page 404's.. see screenshot

### Screenshots:

<img width="460" alt="Screenshot 2024-09-19 at 5 58 31 PM" src="https://github.com/user-attachments/assets/9543f185-eb4d-496c-a3ce-28a371689f00">

### To Reproduce:
1. Go to the vercel hosted page @ https://pass-wine.vercel.app/
2. Log into your pod
3. refresh the page once logged in, this will happen on any page aside from the home/landing page prior to logging in.

### Possible Fix:
add rewrites to vercel.json

### Additional context:
https://blog.probirsarkar.com/fixing-react-router-issues-on-vercel-how-to-handle-client-side-routing-and-404-errors-c4fb78aa1af5

**Comment by leekahung** [comment]
There's still a minor bug, PR #678 should fully resolve this issue.
