### ISSUE TITLE
Add clipboard functionality to pod URLs

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#86]
**Is your feature request related to a problem? Please describe.**
While there's a select user functionality at the moment, there could be times when people just want to copy and paste a user's link.

**Describe the solution you'd like**
Perhaps we could use something like the Clipboard API for what we need.

**Comment by goutham03062001** [comment]
Hello is this issue still opened? 

I would like to work upon this issue.

**Comment by leekahung** [comment]
Hey @goutham03062001. The problem is still pending and I believe Steve on the team is planning to work on it. I think you could discuss with him on discord about this feature.

**Comment by leekahung** [comment]
Hey @goutham03062001, it seems Steve is okay with you working on this issue if you're still interested.

If you wish to contribute to this feature, I think it'll be a great addition to the project, as stated in the feature request. I look forward to your contribution!

**Comment by leekahung** [comment]
Could be useful in a future feature, will close this issue for now. Could potentially a new one related to clipboard when brought up again.
