### ISSUE TITLE
Inactivity message

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#88]
**Is your feature request related to a problem? Please describe.**
More of a "quality of life" feature if anything. But perhaps a user has been inactive for a certain amount of time. Perhaps we could create a small prompt that alerts/remind the user on whether or not they would like to log out since they have not been using PASS for a certain amount of time.

**Describe the solution you'd like**
Perhaps create a modal or a pop-up or something with a message. Could be closed easily.

**Comment by benzelcurry** [comment]
He

**Comment by benzelcurry** [comment]
Sorry, didn't mean to close the issue.

I wanted to ask for clarification regarding this issue. Are you just asking for the modal without the functionality of a timeout feature? Or do you want it to have the timeout as well? I'd like to handle this issue, but just want to be sure of what exactly is needed before I get to work.

**Comment by leekahung** [comment]
Yep. Something like a modal that pops up after, say, x minutes of mouse movement or scrolling and let's people know they're inactive.

**Comment by leekahung** [comment]
Completed as of PR #101. Closing issue.
